Repository CliMA/ClimaAtmos.jl, pull requests merged in 2021-09, with the labels that each got.

#71 Refactor model for better regression testing
  .gitignore
  Project.toml
  examples/shallow_water_toy.jl
  examples/single_column_toy.jl
  src/ClimaAtmos.jl
  src/Domains/Domains.jl
  src/Domains/domain.jl
  src/Domains/make_function_space.jl
  src/Models/Models.jl
  src/Models/make_initial_conditions.jl
  src/Models/model_interface.jl
  src/Models/shallow_water_models/shallow_water_model.jl
  src/Models/single_column_models/single_column_model.jl
  src/Models/splitting.jl
  src/ShallowWaterModels/ShallowWaterModels.jl
  src/ShallowWaterModels/shallow_water_model.jl
  src/Simulations/Simulations.jl
  src/Simulations/simulation.jl
  src/SingleColumnModels/SingleColumnModels.jl
  src/SingleColumnModels/single_column_model.jl
  src/Utils/Utils.jl
  test/Project.toml
  test/runtests.jl
  test/test_cases/initial_conditions/InitialConditions.jl
  test/test_cases/initial_conditions/bickley_jet_2d_plane.jl
  test/test_cases/initial_conditions/cosine_bell_2d.jl
  test/test_cases/initial_conditions/cosine_bell_shallow_water.jl
  test/test_cases/initial_conditions/density_current_2d.jl
  test/test_cases/initial_conditions/dry_rising_bubble_2d.jl
  test/test_cases/initial_conditions/ekman_column_1d.jl
  test/test_cases/run_bickley_jet_2d_plane.jl
  test/test_cases/run_ekman_column_1d.jl
  test/test_regression.jl
  test/test_simulations.jl
  test/test_validation.jl
Labels: enhancement, WIP, do-not-merge-yet

#72 Hotfix for regression tests
  test/test_cases/run_bickley_jet_2d_plane.jl
  test/test_cases/run_ekman_column_1d.jl
  test/test_regression.jl
  test/test_simulations.jl
  test/test_validation.jl
Labels: bug

#73 Refactor initial conditions
  src/Models/Models.jl
  src/Models/model_interface.jl
  src/ShallowWaterModels/shallow_water_model.jl
  src/Simulations/Simulations.jl
  src/Simulations/simulation.jl
  src/SingleColumnModels/single_column_model.jl
  test/runtests.jl
  test/test_cases/initial_conditions/bickley_jet_2d_plane.jl
  test/test_cases/initial_conditions/ekman_column_1d.jl
  test/test_cases/run_bickley_jet_2d_plane.jl
  test/test_cases/run_ekman_column_1d.jl
  test/test_domains.jl
  test/test_regression.jl
  test/test_simulations.jl
  test/test_validation.jl
Labels: enhancement

#75 Reschuffled model folders
  src/ClimaAtmos.jl
  src/Models/Models.jl
  src/Models/ShallowWaterModels/ShallowWaterModels.jl
  src/Models/ShallowWaterModels/shallow_water_model.jl
  src/Models/SingleColumnModels/SingleColumnModels.jl
  src/Models/SingleColumnModels/single_column_model.jl
  test/runtests.jl
Labels: bikeshedding

#78 Clean up run_ekman_column_1d
  test/test_cases/run_ekman_column_1d.jl
Labels: bug

#79 fix plotting for ekman scm
  test/test_cases/run_ekman_column_1d.jl
Labels: bug

#80 Fix an error in the hydrostatic ekman column example
  src/Models/SingleColumnModels/single_column_model.jl
Labels: bug

#81 Add install & run example instructions to the docs and the readme
  README.md
  docs/make.jl
  docs/src/installation_instructions.md
  docs/src/running_instructions.md
Labels: documentation

#84 Update contributor guide
  docs/make.jl
  docs/src/abstractions.md
  docs/src/contributor_guide.md
  docs/src/function_index.md
  docs/src/running_instructions.md
  src/Simulations/simulation.jl
Labels: documentation

#86 Add Base.show for Simulation and Domain
  src/Domains/domain.jl
  src/Simulations/Simulations.jl
  src/Simulations/simulation.jl
Labels: enhancement

#87 add docstrings for domains, models, and simulation modules
  docs/src/contributor_guide.md
  src/Domains/Domains.jl
  src/Domains/domain.jl
  src/Models/ShallowWaterModels/shallow_water_model.jl
  src/Models/SingleColumnModels/single_column_model.jl
  src/Models/model_interface.jl
  src/Simulations/simulation.jl
Labels: documentation

#90 Update the function index for the docs
  docs/src/function_index.md
Labels: documentation

#85 As/callback interface
  Project.toml
  src/Callbacks/Callbacks.jl
  src/Callbacks/callback.jl
  src/ClimaAtmos.jl
  src/Simulations/Simulations.jl
  src/Simulations/simulation.jl
  test/runtests.jl
  test/test_callbacks.jl
  test/test_cases/run_bickley_jet_2d_plane.jl
Labels: enhancement

#94 Hotfix for ClimaCore compatibility
  src/Models/SingleColumnModels/SingleColumnModels.jl
  src/Models/SingleColumnModels/single_column_model.jl
  test/test_cases/initial_conditions/InitialConditions.jl
  test/test_cases/initial_conditions/bickley_jet_2d_plane.jl
Labels: bug

#92 Add 1+1D hybrid domain support
  src/Domains/Domains.jl
  src/Domains/domain.jl
  src/Domains/make_function_space.jl
  test/runtests.jl
  test/test_domains.jl
Labels: enhancement

#108 Update README.md
  README.md
Labels: documentation

#113 fix a bug in make_function_space for hybrid plane
  src/Domains/make_function_space.jl
Labels: bug

#114 Updated workflow to reflect registration of ClimaCore
  .github/workflows/CodeCov.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
Labels: enhancement

#116 Fix a bug in make_function_space.jl
  src/Domains/make_function_space.jl
  test/test_cases/run_bickley_jet_2d_plane.jl
Labels: bug

#117 Update README.md (ClimaCore is now registered)
  README.md
  docs/src/installation_instructions.md
Labels: documentation

#125 Add regression and validation tests for the dry rising bubble test
  test/test_cases/run_dry_rising_bubble_2d.jl
Labels: enhancement
