Repository CliMA/ClimaAtmos.jl, pull requests merged in 2022-11, with the labels that each got.

#1066 Move hyperdiffusion into src
  examples/hybrid/driver.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  perf/benchmark.jl
  src/ClimaAtmos.jl
  src/tendencies/hyperdiffusion.jl
Labels: Refactor, Organization :package:

#1068 Move precomputed quantities into src
  examples/hybrid/staggered_nonhydrostatic_model.jl
  src/ClimaAtmos.jl
  src/precomputed_quantities.jl
Labels: Refactor, Organization :package:

#1055 Add parallel remap script
  .buildkite/pipeline.yml
  examples/hybrid/sphere/remap_pipeline.jl
  examples/hybrid/sphere/remap_pipeline_parallel.jl
Labels: Visualization :art:

#1069 Remove stencil coef converts
  examples/hybrid/staggered_nonhydrostatic_model.jl
Labels: House cleaning :broom:

#1070 Add and use SafeTestsets
  test/Project.toml
  test/aqua.jl
  test/runtests.jl
Labels: Tests

#1064 Upgrade deps
  docs/Manifest.toml
  examples/Manifest.toml
  examples/hybrid/cli_options.jl
  examples/hybrid/schur_complement_W.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  examples/hybrid/types.jl
  perf/Manifest.toml
  perf/benchmark.jl
  regression_tests/ref_counter.jl
Labels: Dependencies :spider_web:

#1072 Move topography into src
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
  src/ClimaAtmos.jl
  src/topography.jl
Labels: Refactor, Organization :package:

#1075 Move gravity wave parameterization into src
  .buildkite/pipeline.yml
  examples/hybrid/driver.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  src/ClimaAtmos.jl
  src/tendencies/gravity_wave_parameterization.jl
  test/gravity_wave_parameterization/gw_test_3d.jl
  test/gravity_wave_parameterization/gw_test_single_column.jl
Labels: Refactor, Organization :package:

#1076 Move post processing into dedicated folder
  .buildkite/comparison/pipeline.sh
  .buildkite/pipeline.yml
  .buildkite/scaling/pipeline.sh
  examples/hybrid/driver.jl
  post_processing/comparison_plots.jl
  post_processing/define_tc_quicklook_profiles.jl
  post_processing/plot_scaling_results.jl
  post_processing/post_processing_funcs.jl
  post_processing/remap/remap_helpers.jl
  post_processing/remap/remap_pipeline.jl
  post_processing/remap/remap_pipeline_parallel.jl
Labels: Refactor, Organization :package:

#1078 Refactor TC init
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/driver.jl
  src/TurbulenceConvection/EDMF_Precipitation.jl
  src/TurbulenceConvection/microphysics_coupling.jl
  src/TurbulenceConvection/thermodynamics.jl
  src/TurbulenceConvection/update_aux.jl
  tc_driver/dycore.jl
Labels: Refactor

#1082 Move radiation tendencies into src
  examples/hybrid/callbacks.jl
  examples/hybrid/driver.jl
  examples/hybrid/radiation_utilities.jl
  src/ClimaAtmos.jl
  src/tendencies/radiation.jl
Labels: Refactor, Organization :package:

#1086 Add timings to init functions
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
Labels: Latency

#1087 Update deps
  docs/Manifest.toml
  examples/Manifest.toml
  ode_compat_examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#1090 Do not cache log_pressure_fun
  examples/hybrid/TurbulenceConvectionUtils.jl
  src/ref_state.jl
Labels: Refactor

#1091 Use dispatch more in `additional_tendency!`
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/driver.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  src/tendencies/forcing/held_suarez.jl
  src/tendencies/forcing/subsidence.jl
  src/tendencies/radiation.jl
Labels: Refactor

#1093 Add function barrier to get_integrator
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
Labels: Latency

#1096 Add AtmosModel type and print summary
  examples/hybrid/callbacks.jl
  examples/hybrid/driver.jl
  examples/hybrid/initial_conditions.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  examples/hybrid/types.jl
  perf/benchmark.jl
  post_processing/post_processing_funcs.jl
  src/InitialConditions/baro_wave.jl
  src/InitialConditions/box.jl
  src/InitialConditions/single_column.jl
  src/InitialConditions/sphere.jl
  src/RRTMGPInterface.jl
  src/model_getters.jl
  src/tendencies/radiation.jl
  src/types.jl
Labels: Refactor

#1097 Add contour diagnostic plots for single column config
  .buildkite/pipeline.yml
  examples/hybrid/driver.jl
  post_processing/define_tc_quicklook_profiles.jl
  src/utilities.jl
  test/runtests.jl
  test/utilities.jl
Labels: Visualization :art:

#1102 Fix contour plots
  post_processing/define_tc_quicklook_profiles.jl
Labels: Visualization :art:

#1110 Unify the clims
  examples/hybrid/driver.jl
  post_processing/define_tc_quicklook_profiles.jl
  regression_tests/ref_counter.jl
Labels: Continuous integration :gear:

#1112 Fix CI, qualify Plots funcs
  post_processing/define_tc_quicklook_profiles.jl
Labels: Continuous integration :gear:

#1111 Cleanup, fix global closure
  examples/hybrid/callbacks.jl
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  src/tendencies/implicit/wfact.jl
Labels: Refactor, bugfix :bug: :hammer:

#1113 Bump minor version for new release
  Project.toml
Labels: Release

#1114 Refactor surface
  examples/hybrid/driver.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  examples/hybrid/types.jl
  src/model_getters.jl
  src/tendencies/vertical_diffusion_boundary_layer.jl
  src/thermo_state.jl
  src/types.jl
Labels: Refactor

#1117 Skip debugging filenames in contour plots
  post_processing/define_tc_quicklook_profiles.jl
Labels: Logging :ledger:

#1118 try adding back plots
  examples/hybrid/driver.jl
Labels: Continuous integration :gear:, Visualization :art:

#1116 compute precipitation tendencies after edmf
  examples/hybrid/driver.jl
  regression_tests/ref_counter.jl
Labels: Microphysics, Debugging :mag::bug:, EDMF :tornado:

#1120 Remove trivial entry in mse tables
  regression_tests/mse_tables.jl
Labels: Continuous integration :gear:

#1123 Add dycore consistency test
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  src/tendencies/implicit/wfact.jl
  src/utilities.jl
Labels: Tests

#1122 Postprocessing: Add integrated 1d KE spectra plots
  post_processing/post_processing_funcs.jl
Labels: enhancement, Visualization :art:

#1124 Add Rico case
  .buildkite/pipeline.yml
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
Labels: Tests

#1125 Add Nieuwstadt case
  .buildkite/pipeline.yml
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  tc_driver/Cases.jl
Labels: Tests

#1127 Use better surface names
  examples/hybrid/TurbulenceConvectionUtils.jl
  tc_driver/Cases.jl
Labels: Naming conventions

#1128 Add ARM SGP
  .buildkite/pipeline.yml
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  tc_driver/Cases.jl
Labels: Tests

#1021 Add implicit EDMF using JFNK
  .buildkite/pipeline.yml
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  examples/hybrid/types.jl
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/closures/entr_detr.jl
  tc_driver/dycore.jl
Labels: AMIP Key result, Time stepping :hourglass:, EDMF :tornado:

#1133 Upgrade deps
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  ode_compat_examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#1135 Add life cycle tan
  .buildkite/pipeline.yml
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  tc_driver/Cases.jl
  tc_driver/generate_namelist.jl
  test/test_parameters.jl
Labels: Tests

#1134 Refactor surface functions
  examples/hybrid/callbacks.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  src/tendencies/vertical_diffusion_boundary_layer.jl
Labels: Refactor, Surface :surfer:

#1137 Remove condition for computing ustar
  .buildkite/pipeline.yml
  tc_driver/Surface.jl
Labels: Refactor

#1141 Remove use of UnPack, update deps
  .dev/Manifest.toml
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/ordinary_diff_eq_bug_fixes.jl
  ode_compat_examples/Manifest.toml
  ode_compat_examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  src/TurbulenceConvection/EDMF_Environment.jl
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/TurbulenceConvection.jl
  tc_driver/Cases.jl
  tc_driver/dycore.jl
  test/Project.toml
Labels: Dependencies :spider_web:, House cleaning :broom:

#1143 Refactor surface
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  src/model_getters.jl
  src/tendencies/vertical_diffusion_boundary_layer.jl
  src/types.jl
Labels: Refactor, Surface :surfer:

#1144 Move zero momentum fluxes flag to edmf model
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/types.jl
  tc_driver/Cases.jl
  tc_driver/Surface.jl
Labels: Refactor

#1146 Remove SurfaceBase
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/closures/perturbation_pressure.jl
  src/TurbulenceConvection/types.jl
  src/TurbulenceConvection/update_aux.jl
  tc_driver/Surface.jl
  tc_driver/dycore.jl
Labels: Refactor, Surface :surfer:

#1152 Add dss helper, prep for CTS
  examples/hybrid/staggered_nonhydrostatic_model.jl
Labels: Refactor

#1151 Fix 1142
  .buildkite/pipeline.yml
  src/tendencies/vertical_diffusion_boundary_layer.jl
Labels: bugfix :bug: :hammer:

#1153 Prep removing fields when unused
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/driver.jl
  src/types.jl
  tc_driver/dycore_variables.jl
Labels: Refactor

#1161 Refactor ICs
  examples/hybrid/driver.jl
  examples/hybrid/initial_conditions.jl
  examples/hybrid/types.jl
  src/InitialConditions/InitialConditions.jl
  src/InitialConditions/baro_wave.jl
  src/InitialConditions/box.jl
  src/InitialConditions/single_column.jl
  src/InitialConditions/sphere.jl
Labels: Refactor

#1163 Prep for edmf on a sphere
  examples/hybrid/TurbulenceConvectionUtils.jl
  src/types.jl
  tc_driver/Surface.jl
Labels: Refactor

#1164 Add perf mode flag and experimental perf job
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/types.jl
  perf/flame.jl
  regression_tests/ref_counter.jl
  src/InitialConditions/InitialConditions.jl
  src/InitialConditions/baro_wave.jl
  src/InitialConditions/box.jl
  src/InitialConditions/single_column.jl
  src/InitialConditions/sphere.jl
  src/model_getters.jl
  src/types.jl
Labels: Performance monitoring :rocket: :mag:

#1165 Remove use of namelist
  examples/hybrid/driver.jl
  examples/hybrid/parameter_set.jl
Labels: Refactor

#1154 Upgrade to Julia 1.8.3
  .buildkite/comparison/pipeline.sh
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/scaling/pipeline.sh
  .dev/Manifest.toml
  README.md
  bors.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/README.md
  ode_compat_examples/Manifest.toml
  perf/Manifest.toml
  post_processing/remap/remap_pipeline.jl
Labels: Dependencies :spider_web:

#1167 Add trmm 0-moment case to CI
  .buildkite/pipeline.yml
  examples/hybrid/callbacks.jl
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  src/tendencies/precipitation.jl
Labels: Microphysics

#1108 Move precipitation tendencies to dycore
  regression_tests/ref_counter.jl
  src/tendencies/precipitation.jl
  tc_driver/dycore.jl
Labels: Refactor, Microphysics, EDMF :tornado:

#1171 Union split thermo calls over moisture model
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/TurbulenceConvection/thermodynamics.jl
  src/TurbulenceConvection/update_aux.jl
Labels: Performance, Stability :surfer:

#1162 Refactor energy ICs
  src/InitialConditions/InitialConditions.jl
  src/InitialConditions/baro_wave.jl
  src/InitialConditions/box.jl
  src/InitialConditions/single_column.jl
  src/InitialConditions/sphere.jl
Labels: Refactor

#1170 Use try-catch around solve to plot crashed tc profiles
  examples/hybrid/driver.jl
Labels: Workflow :gear: :ocean:
