Repository CliMA/ClimaAtmos.jl, pull requests merged in 2022-09, with the labels that each got.

#611 Only move results to main in case of self reference
  regression_tests/move_output.jl
Labels: Regression tests

#797 Remove TC dep
  perf/Manifest.toml
  perf/Project.toml
  test/Project.toml
Labels: Dependencies :spider_web:

#808 Use ProfileCanvas, rm ChromeProfileFormat
  .buildkite/pipeline.yml
  perf/Manifest.toml
  perf/Project.toml
  perf/flame.jl
  perf/profile_canvas_patch.jl
Labels: Performance monitoring :rocket: :mag:

#814 Always move performance benchmarks
  regression_tests/move_output.jl
Labels: Performance monitoring :rocket: :mag:, bugfix :bug: :hammer:

#820 Restart regression tests
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
Labels: Regression tests

#822 Bump minor version for new release
  Project.toml
Labels: Release

#828 Add allocation tests, add threaded flame graph
  .buildkite/pipeline.yml
  perf/flame.jl
Labels: Tests, Performance

#831 Add flame graph for callbacks
  .buildkite/pipeline.yml
  perf/flame.jl
Labels: Performance monitoring :rocket: :mag:

#826 Unify wfact, cache enthalpy
  examples/hybrid/staggered_nonhydrostatic_model.jl
  examples/hybrid/types.jl
  perf/flame.jl
Labels: Refactor, Performance

#834 Add ARS343 flame graph
  .buildkite/pipeline.yml
  perf/flame.jl
Labels: Performance

#816 Add output for debugging TC in CA
  .buildkite/pipeline.yml
  examples/hybrid/callbacks.jl
  examples/hybrid/cli_options.jl
  examples/hybrid/define_tc_quicklook_profiles.jl
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
Labels: Debugging :mag::bug:

#839 update to julia 1.8.1
  .buildkite/comparison/generate_comparison_pipeline.sh
  .buildkite/comparison/pipeline.yml
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/scaling/pipeline.yml
  .github/workflows/CodeCov.yml
  .github/workflows/ci.yml
  .github/workflows/julia_formatter.yml
  README.md
  bors.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#841 Update to CloudMicrophysics v 0.9.0
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/common_spaces.jl
  examples/hybrid/define_post_processing.jl
  perf/Manifest.toml
  perf/Project.toml
  test/Project.toml
Labels: Dependencies :spider_web:

#842 Add at-time to distributed solve
  examples/hybrid/driver.jl
  perf/flame.jl
Labels: Performance monitoring :rocket: :mag:

#844 Unify implicit_tendency
  examples/hybrid/staggered_nonhydrostatic_model.jl
  examples/hybrid/types.jl
  perf/flame.jl
Labels: Deleting duplication

#847 Unify exp vert adv
  .buildkite/pipeline.yml
  examples/hybrid/driver.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  perf/flame.jl
Labels: Deleting duplication

#848 Update dependencies
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  perf/flame.jl
Labels: Dependencies :spider_web:

#836 Aim allocation monitoring at perf targets
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  perf/allocs.jl
  perf/allocs_per_case.jl
  perf/flame.jl
Labels: Performance monitoring :rocket: :mag:

#855 fix for issue 854
  examples/hybrid/callbacks.jl
Labels: bugfix :bug: :hammer:

#858 Make up_deps script more robust
  .dev/up_deps.jl
Labels: Workflow :gear: :ocean:

#843 Fix distributed log
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/config_log.jl
  examples/hybrid/driver.jl
  tc_driver/main.jl
Labels: Logging :ledger:

#866 Remove allocs and use of parent in HS tendency
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  perf/Manifest.toml
  perf/flame.jl
Labels: Performance, Memory :brain:

#868 Change default ode solver to ARS343
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  perf/flame.jl
  regression_tests/mse_tables.jl
Labels: Time stepping :hourglass:

#860 CLI option: nh_poly help string
  examples/hybrid/cli_options.jl
Labels: documentation

#870 Update deps and formatter compat
  .dev/Manifest.toml
  .dev/Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#869 CI: double dt
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  perf/flame.jl
Labels: Continuous integration :gear:, Automation :gear:
