Repository CliMA/ClimaAtmos.jl, pull requests merged in 2022-10, with the labels that each got.

#881 Fix callback in long runs
  examples/hybrid/callbacks.jl
Labels: bugfix :bug: :hammer:

#880 Cache flux BCs
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  perf/flame.jl
Labels: Performance

#882 fix a bug in save_to_disk_func
  .buildkite/pipeline.yml
  examples/hybrid/callbacks.jl
Labels: bugfix :bug: :hammer:

#883 Refactor surface scheme
  examples/hybrid/driver.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  examples/hybrid/types.jl
Labels: Refactor

#886 specify cloud properites in the boundary layer for radiation
  .buildkite/pipeline.yml
  examples/RRTMGPInterface.jl
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
Labels: bugfix :bug: :hammer:

#890 Upgrade deps
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#884 Refactor vert diff BL tendency
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  perf/flame.jl
  regression_tests/mse_tables.jl
Labels: Performance

#894 Widen allocation monitoring
  examples/hybrid/hyperdiffusion.jl
  perf/allocs.jl
Labels: Allocations

#898 Suppress allocation table
  .buildkite/pipeline.yml
  regression_tests/mse_tables.jl
Labels: Continuous integration :gear:, Workflow :gear: :ocean:, Allocations

#900 Add and fix some Aqua tests
  src/TurbulenceConvection/types.jl
  test/Project.toml
  test/runtests.jl
Labels: Tests

#906 Remove unused code
  tc_driver/TimeStepping.jl
  tc_driver/callbacks.jl
  tc_driver/common_spaces.jl
  tc_driver/dycore.jl
  tc_driver/main.jl
  tc_driver/parameter_set.jl
Labels: House cleaning :broom:

#909 Remove some unused code
  src/TurbulenceConvection/utility_functions.jl
  tc_driver/Artifacts.toml
  tc_driver/Cases.jl
  tc_driver/NetCDFIO.jl
  tc_driver/artifact_funcs.jl
  tc_driver/compute_diagnostics.jl
  tc_driver/download_artifacts.jl
  tc_driver/generate_namelist.jl
  test/test_parameters.jl
Labels: Refactor, House cleaning :broom:

#915 Update dependencies
  .buildkite/pipeline.yml
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:, Allocations

#908 Add profiles plots to all TC tests, make them appear first in artifacts
  .buildkite/pipeline.yml
  examples/hybrid/define_tc_quicklook_profiles.jl
  regression_tests/ref_counter.jl
Labels: enhancement, Tests

#914 revert 977
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/update_aux.jl
Labels: bugfix :bug: :hammer:

#920 Remove k-loop in grid-mean computations
  tc_driver/dycore.jl
Labels: Refactor

#921 Remove more k-loops in edmf
  src/TurbulenceConvection/EDMF_Updrafts.jl
  src/TurbulenceConvection/EDMF_functions.jl
Labels: Refactor

#905 Unify kinetic energy
  regression_tests/ref_counter.jl
  src/TurbulenceConvection/dycore_api.jl
  src/TurbulenceConvection/update_aux.jl
  tc_driver/dycore.jl
  tc_driver/dycore_variables.jl
Labels: Refactor

#917 Cache some edmf variables
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/update_aux.jl
  src/TurbulenceConvection/variables.jl
Labels: Refactor, Performance, Allocations

#912 Fuse some bycolumn loops
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/driver.jl
  examples/hybrid/radiation_utilities.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
Labels: Refactor, Performance

#937 Move RRTMGPInterface into ClimaAtmos/src
  .dev/Manifest.toml
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/hybrid/driver.jl
  examples/hybrid/radiation_utilities.jl
  examples/hybrid/types.jl
  perf/Manifest.toml
  src/ClimaAtmos.jl
  src/RRTMGPInterface.jl
Labels: Refactor

#938 Remove some k-loops
  tc_driver/dycore.jl
Labels: Refactor

#933 Compute velocities before they are used
  regression_tests/mse_tables.jl
  src/TurbulenceConvection/update_aux.jl
Labels: Consistency :dart:

#895 Prep unifying dycore and edmf types
  examples/hybrid/types.jl
  src/ClimaAtmos.jl
  src/model_getters.jl
  src/types.jl
Labels: Refactor

#910 Make sure mse values are reset when incrementing ref counter
  .buildkite/pipeline.yml
  regression_tests/test_reset.jl
Labels: Workflow :gear: :ocean:, Regression tests

#940 Remove unused code
  examples/hybrid/TurbulenceConvectionUtils.jl
  src/TurbulenceConvection/variables.jl
  tc_driver/dycore_variables.jl
Labels: House cleaning :broom:

#942 Fix some vector conversions
  src/TurbulenceConvection/Fields.jl
  src/TurbulenceConvection/update_aux.jl
Labels: bugfix :bug: :hammer:

#959 Move tc code into src
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/callbacks.jl
  src/TurbulenceConvection/types.jl
Labels: Refactor, Latency

#962 Update manifests
  .buildkite/comparison/pipeline.sh
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/scaling/pipeline.sh
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#964 Clean up forcing
  tc_driver/Cases.jl
  tc_driver/Forcing.jl
Labels: Refactor, House cleaning :broom:

#965 Lower allocation limit
  perf/flame.jl
Labels: Tests, Allocations

#968 Remove TC internals in thermo state computation
  examples/hybrid/TurbulenceConvectionUtils.jl
  regression_tests/ref_counter.jl
  tc_driver/dycore.jl
Labels: Refactor

#966 Rm TC internals from thermo state computation
  examples/hybrid/TurbulenceConvectionUtils.jl
  tc_driver/dycore.jl
Labels: Refactor

#971 Refactor radiation
  Project.toml
  examples/hybrid/callbacks.jl
  examples/hybrid/driver.jl
  examples/hybrid/radiation_utilities.jl
  examples/hybrid/types.jl
  src/RRTMGPInterface.jl
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/model_getters.jl
  src/types.jl
  tc_driver/Cases.jl
  tc_driver/Radiation.jl
  tc_driver/dycore.jl
Labels: Refactor

#974 Refactor radiation
  .buildkite/pipeline.yml
  examples/Manifest.toml
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/classify_case.jl
  examples/hybrid/driver.jl
  examples/hybrid/radiation_utilities.jl
  perf/Manifest.toml
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/model_getters.jl
  src/types.jl
  tc_driver/Cases.jl
  tc_driver/Radiation.jl
  tc_driver/dycore.jl
  tc_driver/dycore_variables.jl
Labels: Refactor

#960 Move tc radiation into dycore
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/radiation_utilities.jl
  regression_tests/ref_counter.jl
  tc_driver/Cases.jl
  tc_driver/dycore.jl
Labels: Refactor

#986 Delete unused code
  tc_driver/Cases.jl
Labels: House cleaning :broom:

#984 Enable dispatching thermo state on compressibility model
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/callbacks.jl
  examples/hybrid/define_post_processing.jl
  examples/hybrid/driver.jl
  examples/hybrid/radiation_utilities.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  examples/hybrid/thermo_state.jl
  regression_tests/ref_counter.jl
  src/TurbulenceConvection/types.jl
  tc_driver/dycore.jl
Labels: Refactor, Thermodynamics :fire:

#758 Add job with check bounds
  .buildkite/pipeline.yml
Labels: Correctness :pencil2:

#990 Move viscous sponge into src
  examples/hybrid/driver.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  src/ClimaAtmos.jl
  src/tendencies/viscous_sponge.jl
Labels: Organization :package:

#993 Move advection into src, make implicit tendency with colidx
  examples/hybrid/linsolve_test.jl
  examples/hybrid/schur_complement_W.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  src/ClimaAtmos.jl
  src/tendencies/advection.jl
  src/utilities.jl
Labels: Organization :package:

#996 Move HS and rayleigh sponge into src
  examples/hybrid/driver.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  examples/hybrid/utilities.jl
  src/ClimaAtmos.jl
  src/tendencies/held_suarez.jl
  src/tendencies/rayleigh_sponge.jl
  src/utilities.jl
Labels: Organization :package:

#999 Adjust soft-fail jobs
  .buildkite/pipeline.yml
Labels: Continuous integration :gear:

#1000 Move thermo_state into src
  examples/hybrid/callbacks.jl
  examples/hybrid/define_post_processing.jl
  examples/hybrid/radiation_utilities.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  src/ClimaAtmos.jl
  src/thermo_state.jl
Labels: Organization :package:

#1001 Move `vertical_diffusion_boundary_layer_tendency!` to src/
  examples/hybrid/driver.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  src/ClimaAtmos.jl
  src/tendencies/vertical_diffusion_boundary_layer.jl
Labels: Organization :package:

#1004 Remove no longer needed patch
  perf/flame.jl
  perf/profile_canvas_patch.jl
Labels: Performance monitoring :rocket: :mag:

#1007 Move implicit tendency to src
  examples/hybrid/staggered_nonhydrostatic_model.jl
  src/ClimaAtmos.jl
  src/tendencies/implicit_tendency.jl
Labels: Organization :package:

#1008 Move held suarez into forcing subfolder
  src/ClimaAtmos.jl
  src/tendencies/forcing/held_suarez.jl
Labels: Organization :package:

#1009 Remove unused functions
  src/TurbulenceConvection/thermodynamics.jl
Labels: House cleaning :broom:

#1012 Try fixing non-unique job IDs
  .buildkite/pipeline.yml
Labels: bugfix :bug: :hammer:

#1013 Refactor compute_ref_state
  examples/hybrid/types.jl
  tc_driver/dycore.jl
Labels: Refactor

#1018 Merge subsidence into dycore tendencies
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  examples/hybrid/types.jl
  src/ClimaAtmos.jl
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/thermodynamics.jl
  src/TurbulenceConvection/update_aux.jl
  src/model_getters.jl
  src/tendencies/forcing/subsidence.jl
  src/types.jl
  tc_driver/Cases.jl
  tc_driver/dycore.jl
  tc_driver/dycore_variables.jl
Labels: Refactor, Organization :package:

#1020 Increase mem request for longrun
  .buildkite/longruns/pipeline.yml
Labels: Long runs :running_woman:

#1022 Move large-scale advection forcing to src
  .buildkite/pipeline.yml
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
  regression_tests/ref_counter.jl
  src/ClimaAtmos.jl
  src/TurbulenceConvection/diagnostics.jl
  src/model_getters.jl
  src/tendencies/forcing/large_scale_advection.jl
  src/types.jl
  tc_driver/Cases.jl
  tc_driver/dycore.jl
  tc_driver/dycore_variables.jl
Labels: Refactor, House cleaning :broom:, Organization :package:

#1023 Remove unused fields
  examples/hybrid/initial_conditions.jl
Labels: House cleaning :broom:

#1024 Remove unused fields
  src/TurbulenceConvection/diagnostics.jl
  src/TurbulenceConvection/name_aliases.jl
  tc_driver/dycore_variables.jl
Labels: House cleaning :broom:

#1026 Unify edmf coriolis
  .buildkite/pipeline.yml
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
  src/ClimaAtmos.jl
  src/TurbulenceConvection/utility_functions.jl
  src/model_getters.jl
  src/tendencies/edmf_coriolis.jl
  src/types.jl
  tc_driver/Cases.jl
  tc_driver/dycore.jl
  tc_driver/generate_namelist.jl
Labels: Refactor, Organization :package:

#1030 Remove `real_face_indices`
  src/TurbulenceConvection/Grid.jl
  tc_driver/Cases.jl
  tc_driver/initial_conditions.jl
Labels: Refactor

#1014 Integrate spectra calculator for moist baro wave ex
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/define_post_processing.jl
Labels: Visualization :art:

#1033 Relax assumptions in ref_state
  examples/hybrid/TurbulenceConvectionUtils.jl
  src/ClimaAtmos.jl
  src/ref_state.jl
  tc_driver/dycore.jl
Labels: Refactor

#1037 Try to fix edmf inconsistency job
  examples/hybrid/TurbulenceConvectionUtils.jl
  src/ref_state.jl
Labels: Refactor

#1038 Add `debug_state` function
  src/utilities.jl
Labels: Debugging :mag::bug:

#1032 Use newer limiter interface
  examples/hybrid/staggered_nonhydrostatic_model.jl
Labels: Logging :ledger:

#1045 Ensure edmf consistency passes
  .buildkite/pipeline.yml
Labels: Tests

#1047 remove DiffEqOperators dependency
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  perf/allocs.jl
  test/Project.toml
Labels: Dependencies :spider_web:, House cleaning :broom:

#1046 Remove unused noneq
  src/TurbulenceConvection/EDMF_Environment.jl
  src/TurbulenceConvection/EDMF_Updrafts.jl
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/TurbulenceConvection/types.jl
  src/TurbulenceConvection/update_aux.jl
  src/TurbulenceConvection/variables.jl
  src/tendencies/forcing/large_scale_advection.jl
  tc_driver/dycore.jl
  tc_driver/dycore_variables.jl
Labels: Microphysics, EDMF :tornado:

#1049 Rename microphysics to precipitation
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
  src/ClimaAtmos.jl
  src/model_getters.jl
  src/tendencies/precipitation.jl
  src/types.jl
Labels: Refactor, Naming conventions

#1052 Add allocation monitoring to long runs
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
Labels: Performance monitoring :rocket: :mag:

#1048 Upgrade to latest thermodynamics
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  regression_tests/ref_counter.jl
  test/Project.toml
Labels: Dependencies :spider_web:, Thermodynamics :fire:

#1054 Update the TRMM long run flags (adds --rad_flux TRMM)
  .buildkite/longruns/pipeline.yml
Labels: Continuous integration :gear:

#1053 Add invalidations report
  .buildkite/pipeline.yml
  perf/Manifest.toml
  perf/Project.toml
  perf/invalidations.jl
Labels: Performance monitoring :rocket: :mag:

#1051 Refactor remapping
  examples/hybrid/define_post_processing.jl
  examples/hybrid/driver.jl
  examples/hybrid/remap_helpers.jl
  examples/hybrid/sphere/remap_pipeline.jl
Labels: Refactor

#1056 Remove use of `case` and `real_center_indices`
  examples/hybrid/TurbulenceConvectionUtils.jl
  src/TurbulenceConvection/EDMF_functions.jl
  tc_driver/Cases.jl
  tc_driver/initial_conditions.jl
Labels: Refactor

#1059 Remove unused namelist parameters
  tc_driver/generate_namelist.jl
Labels: House cleaning :broom:

#1060 Refactor surface and ICs
  examples/hybrid/TurbulenceConvectionUtils.jl
  src/TurbulenceConvection/turbulence_functions.jl
  src/TurbulenceConvection/update_aux.jl
  tc_driver/Cases.jl
  tc_driver/Surface.jl
Labels: Refactor

#1062 Rm THERMO_VAR env variable in remap pipeline
  examples/README.md
  examples/hybrid/sphere/remap_pipeline.jl
Labels: Refactor

#1065 Add process filename for allocs table in lr dir
  perf/allocs.jl
Labels: Performance monitoring :rocket: :mag:

#1061 Remove use of real_center_indices
  examples/hybrid/TurbulenceConvectionUtils.jl
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/TurbulenceConvection/update_aux.jl
  tc_driver/Cases.jl
Labels: Refactor
