Repository CliMA/ClimaAtmos.jl, pull requests merged in 2022-05, with the labels that each got.

#379 Set random seed
  examples/hybrid/driver.jl
Labels: Reproducibility

#359 Store dt in parameter set for microphysics parameter
  examples/hybrid/driver.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  post_processing/mse_tables.jl
Labels: Performance

#381 Up TC compat
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/TCexample.jl
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#394 Unify some driver pieces
  .buildkite/pipeline.yml
  examples/hybrid/define_post_processing.jl
  examples/hybrid/driver.jl
  examples/hybrid/sphere/baroclinic_wave_rhoe_equilmoist_radiation.jl
  examples/hybrid/sphere/single_column_radiative_equilibrium.jl
Labels: Patterns

#397 Get cli options in main driver
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
Labels: Patterns

#400 Truncate stack traces
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/truncate_stack_traces.jl
Labels: Logging :ledger:

#406 Remove non-driver examples
  .buildkite/pipeline.yml
  examples/hybrid/box/bubble_3d_invariant_rhoe.jl
  examples/hybrid/box/bubble_3d_invariant_rhotheta.jl
  examples/hybrid/box/bubble_3d_rhotheta.jl
  examples/hybrid/plane/density_current_2d_flux_form.jl
  examples/hybrid/plane/density_current_2dinvariant_rhoe.jl
  examples/hybrid/plane/density_current_2dinvariant_rhotheta.jl
Labels: Continuous integration :gear:

#403 Prep for removing TEST_NAME
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/sphere/README.md
  examples/hybrid/sphere/baroclinic_wave_rhoe.jl
  examples/hybrid/sphere/baroclinic_wave_rhoe_equilmoist.jl
  examples/hybrid/sphere/baroclinic_wave_rhoe_equilmoist_radiation.jl
  examples/hybrid/sphere/baroclinic_wave_rhotheta.jl
  examples/hybrid/sphere/held_suarez_rhoe.jl
  examples/hybrid/sphere/held_suarez_rhoe_equilmoist.jl
  examples/hybrid/sphere/held_suarez_rhoe_int.jl
  examples/hybrid/sphere/held_suarez_rhoe_int_equilmoist.jl
  examples/hybrid/sphere/held_suarez_rhotheta.jl
  examples/hybrid/sphere/single_column_radiative_equilibrium.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  perf/allocs.jl
Labels: Refactor

#411 Remove duplicate example and unused example generator
  .dev/pipeline_examples_generator.jl
  examples/hybrid/sphere/solid_body_rotation_3d.jl
Labels: House cleaning :broom:

#417 Add config flag, move column parts to driver
  .buildkite/pipeline.yml
  examples/common_spaces.jl
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/sphere/single_column_radiative_equilibrium.jl
Labels: Refactor

#414 Fix documentation, make docs strict
  docs/make.jl
  docs/src/function_index.md
  src/Domains/domain.jl
  src/Models/Models.jl
Labels: documentation

#415 Auto-document CL arguments
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/src/cl_args.jl
  docs/src/cl_args.md
Labels: documentation

#420 Remove TEST_NAME
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  examples/hybrid/classify_case.jl
  examples/hybrid/cli_options.jl
  examples/hybrid/define_post_processing.jl
  examples/hybrid/driver.jl
  examples/hybrid/sphere/README.md
  perf/allocs.jl
Labels: Refactor

#425 Move and update readme
  examples/README.md
  examples/hybrid/sphere/README.md
Labels: documentation

#430 Improve interactivity, conditionally define parsed_args
  examples/hybrid/driver.jl
Labels: Interactivity

#429 Update Project toml and Manifest files.
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  perf/Project.toml
  test/Project.toml
Labels: Dependencies :spider_web:

#432 add aquaplanet gray radiation
  .buildkite/pipeline.yml
  examples/hybrid/driver.jl
Labels: AMIP Key result

#422 Add time_to_string func for cl args
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
Labels: Refactor

#442 Define and use some types
  examples/hybrid/define_post_processing.jl
  examples/hybrid/driver.jl
  examples/hybrid/radiation_utilities.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  examples/hybrid/types.jl
Labels: AMIP Key result

#449 Centralize clima params def and construction
  examples/hybrid/driver.jl
  examples/hybrid/parameter_set.jl
  examples/hybrid/radiation_utilities.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  examples/hybrid/utilities.jl
Labels: Refactor

#450 Up TC compat and deps
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/TCexample.jl
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#453 Up deps
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#436 Centralize output folder
  examples/hybrid/driver.jl
Labels: House cleaning :broom:

#439 Add performance monitoring for distributed simulations.
  .buildkite/scaling/README.md
  .buildkite/scaling/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/plot_scaling_results.jl
Labels: Performance monitoring :rocket: :mag:

#457 Remove reduntant @timev for distributed timer.
  examples/hybrid/driver.jl
Labels: Continuous integration :gear:, Performance monitoring :rocket: :mag:

#461 Disable depot path for long runs
  .buildkite/longruns/pipeline.yml
Labels: Long runs :running_woman:

#462 Fix overwriting CL arguments
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
Labels: bugfix :bug: :hammer:

#467 fix type error in rayleigh sponge
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
Labels: bugfix :bug: :hammer:

#475 Cap DiffEqBase in test env
  .buildkite/pipeline.yml
  test/Project.toml
Labels: Continuous integration :gear:, Dependencies :spider_web:

#470 Temporarily skip cleanup for debugging
  examples/hybrid/define_post_processing.jl
Labels: Debugging :mag::bug:

#478 Upgrade some dependencies
  docs/Manifest.toml
  docs/Project.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/TCexample.jl
  perf/Manifest.toml
  perf/Project.toml
Labels: Dependencies :spider_web:

#433 Unify TC into driver
  .buildkite/pipeline.yml
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/classify_case.jl
  examples/hybrid/cli_options.jl
  examples/hybrid/define_post_processing.jl
  examples/hybrid/driver.jl
  examples/hybrid/parameter_set.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  examples/hybrid/types.jl
  post_processing/mse_tables.jl
  post_processing/ref_counter.jl
Labels: AMIP Key result

#481 Reset MSE values
  post_processing/mse_tables.jl
Labels: Continuous integration :gear:

#486 Upgrade deps
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#488 add some simulations with sponge
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
Labels: bugfix :bug: :hammer:

#487 Change name from rhoe to rhoe_tot
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/scaling/pipeline.yml
  examples/hybrid/define_post_processing.jl
  examples/hybrid/driver.jl
  examples/hybrid/hyperdiffusion.jl
  examples/hybrid/radiation_utilities.jl
  examples/hybrid/schur_complement_W.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  examples/hybrid/sphere/remap_pipeline.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  post_processing/mse_tables.jl
  post_processing/ref_counter.jl
Labels: Naming conventions

#498 Update dependencies
  .buildkite/pipeline.yml
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/classify_case.jl
  examples/hybrid/driver.jl
  examples/hybrid/parameter_set.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  perf/Manifest.toml
  perf/Project.toml
  post_processing/mse_tables.jl
  post_processing/ref_counter.jl
  src/Models/Nonhydrostatic2DModels/equations_cache.jl
  src/Models/Nonhydrostatic2DModels/equations_precipitation.jl
  test/Project.toml
Labels: Dependencies :spider_web:
