Repository CliMA/ClimaAtmos.jl, pull requests merged in 2022-04, with the labels that each got.

#280 Use Julia Depot, add buildkite groups
  .buildkite/pipeline.yml
Labels: Continuous integration :gear:

#286 Add long run job to buildkite
  .buildkite/longruns/pipeline.yml
Labels: Tests

#291 Add a pipeline example generator script
  .dev/pipeline_examples_generator.jl
  examples/hybrid/cli_options.jl
Labels: Automation :gear:

#294 Update pipeline, use output dir from cli options
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  .dev/pipeline_examples_generator.jl
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/sphere/README.md
Labels: Refactor

#303 Add job_id to cli opts, use instead of output_dir
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
Labels: Refactor

#313 non-const test name, improve jobid, git ignore .json
  .gitignore
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
Labels: Refactor, Miscellaneous :shrug:

#309 Check in examples Manifest.toml
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  .dev/Manifest.toml
  .gitignore
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Reproducibility

#317 Make enable_threading a cli option, and use for long runs
  .buildkite/longruns/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/sphere/README.md
Labels: Refactor

#318 Add some perf monitoring scripts
  .buildkite/pipeline.yml
  perf/Manifest.toml
  perf/Project.toml
  perf/allocs.jl
  perf/allocs_per_case.jl
  perf/benchmark.jl
  perf/flame.jl
Labels: Performance monitoring :rocket: :mag:

#319 Specify slurm_cpus_per_task env, try larger dt, for long runs
  .buildkite/longruns/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/sphere/baroclinic_wave_rhoe.jl
  examples/hybrid/sphere/baroclinic_wave_rhoe_equilmoist.jl
  examples/hybrid/sphere/baroclinic_wave_rhotheta.jl
  examples/hybrid/sphere/held_suarez_rhoe.jl
  examples/hybrid/sphere/held_suarez_rhoe_equilmoist.jl
  examples/hybrid/sphere/held_suarez_rhoe_int.jl
  examples/hybrid/sphere/held_suarez_rhoe_int_equilmoist.jl
  examples/hybrid/sphere/held_suarez_rhotheta.jl
  examples/hybrid/sphere/held_suarez_rhotheta_tempest.jl
Labels: Long runs :running_woman:

#312 Add regression infrastructure
  .buildkite/pipeline.yml
  examples/hybrid/driver.jl
  post_processing/NCRegressionTests.jl
  post_processing/compute_mse.jl
  post_processing/move_output.jl
  post_processing/mse_tables.jl
  post_processing/print_new_mse.jl
Labels: Continuous integration :gear:, Tests

#320 Add .dev/up_deps.jl script
  .dev/up_deps.jl
Labels: Workflow :gear: :ocean:

#321 Hook in regression tests
  examples/hybrid/driver.jl
  post_processing/compute_mse.jl
Labels: Continuous integration :gear:

#257 bring back external boundary conditons
  Project.toml
  src/BoundaryConditions/BoundaryConditions.jl
  src/BoundaryConditions/flux_calculations.jl
  src/BoundaryConditions/flux_conditions.jl
  src/Models/Nonhydrostatic3DModels/Nonhydrostatic3DModels.jl
  src/Models/Nonhydrostatic3DModels/equations_vertical_diffusion.jl
  src/Models/Nonhydrostatic3DModels/nonhydrostatic_3d_model.jl
  test/Project.toml
  test/test_cases/run_3d_baroclinic_wave.jl
Labels: ASAP

#325 Opt out of regression tests by default
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  post_processing/mse_tables.jl
Labels: Refactor, Continuous integration :gear:

#289 add docs for equations
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/src/equations.md
Labels: documentation

#334 Make regression tests more flexible
  .buildkite/pipeline.yml
  post_processing/compute_mse.jl
  post_processing/move_output.jl
  post_processing/print_new_ref_counter.jl
  post_processing/ref_counter.jl
Labels: Continuous integration :gear:, design, Workflow :gear: :ocean:

#331 Add regression test readme, improve documentation
  post_processing/README.md
  post_processing/compute_mse.jl
  post_processing/print_new_ref_counter.jl
Labels: documentation

#338 Upgrade to latest Thermodynamics
  .dev/up_deps.jl
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/sphere/baroclinic_wave_rhoe.jl
  examples/hybrid/sphere/baroclinic_wave_rhotheta.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  perf/Manifest.toml
  perf/Project.toml
  src/Models/Nonhydrostatic2DModels/Nonhydrostatic2DModels.jl
  src/Models/Nonhydrostatic2DModels/equations_cache.jl
  src/Models/Nonhydrostatic3DModels/Nonhydrostatic3DModels.jl
  src/Models/Nonhydrostatic3DModels/equations_pressure.jl
  src/Models/SingleColumnModels/SingleColumnModels.jl
  src/Models/SingleColumnModels/equations_pressure.jl
  src/Utils/InitialConditions/InitialConditions.jl
  src/Utils/InitialConditions/init_2d_moist_bubble.jl
  src/Utils/InitialConditions/init_2d_precipitating_bubble.jl
  test/Project.toml
Labels: Dependencies :spider_web:

#340 Improve log output
  .dev/up_deps.jl
  examples/hybrid/driver.jl
  post_processing/compute_mse.jl
Labels: Logging :ledger:

#347 add latent heat to surface energy flux
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  post_processing/mse_tables.jl
Labels: bug

#336 Docs: Typo fix in Equations
  docs/src/equations.md
Labels: documentation

#360 Fix bug in printing mse tables
  post_processing/print_new_mse.jl
Labels: bugfix :bug: :hammer:

#358 Add cli options, prep to unify driver
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/sphere/README.md
Labels: Refactor

#370 Add/manage compat entries
  .buildkite/longruns/pipeline.yml
  Project.toml
  examples/Project.toml
  perf/Project.toml
  test/Project.toml
Labels: Dependencies :spider_web:

#371 Improve docs and logging
  post_processing/README.md
  post_processing/print_new_mse.jl
Labels: documentation, Logging :ledger:

#366 Update the regression test logic
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/driver.jl
  perf/Manifest.toml
  post_processing/compute_mse.jl
  post_processing/mse_tables.jl
Labels: Continuous integration :gear:, Regression tests
