Repository CliMA/ClimaAtmos.jl, pull requests merged in 2022-08, with the labels that each got.

#730 Increase mem for test env job, bump ref counter
  .buildkite/pipeline.yml
  regression_tests/ref_counter.jl
Labels: Continuous integration :gear:

#729 Fix saveat
  examples/hybrid/callbacks.jl
  examples/hybrid/types.jl
  regression_tests/mse_tables.jl
Labels: Long runs :running_woman:

#667 Remove global closure
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
Labels: Refactor

#733 Update perf target and cleanup
  .buildkite/pipeline.yml
  examples/hybrid/driver.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  examples/hybrid/types.jl
  perf/flame.jl
Labels: House cleaning :broom:, Performance monitoring :rocket: :mag:

#734 Upgrade deps
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:, Performance

#735 Add printing of basic time info
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
Labels: Logging :ledger:

#732 Updates compat entries, and upgrade deps
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  test/Project.toml
Labels: Dependencies :spider_web:

#738 Make sure overloading, hack `calc_tderivative!`
  examples/hybrid/driver.jl
  examples/ordinary_diff_eq_bug_fixes.jl
Labels: Performance

#740 Fix flame graphs
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  perf/flame.jl
Labels: Performance monitoring :rocket: :mag:, bugfix :bug: :hammer:

#749 Upgrade deps, add mem to flame job
  .buildkite/pipeline.yml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  regression_tests/mse_tables.jl
  src/Simulations/Simulations.jl
Labels: Dependencies :spider_web:, Performance

#753 Optimize some pow calls
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  examples/hybrid/utilities.jl
  regression_tests/mse_tables.jl
Labels: Performance

#751 Split out ICs to separate file
  examples/hybrid/initial_conditions.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
Labels: Organization :package:

#772 Add unthreaded job to longrun
  .buildkite/longruns/pipeline.yml
  examples/hybrid/cli_options.jl
Labels: Performance monitoring :rocket: :mag:, Long runs :running_woman:

#775 Upgrade deps
  .buildkite/pipeline.yml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  regression_tests/mse_tables.jl
Labels: Dependencies :spider_web:

#724 Aj/hydrostatic profiles
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  tc_driver/Cases.jl
  tc_driver/dycore.jl
Labels: AMIP Key result

#784 Fix some names
  examples/hybrid/linsolve_test.jl
  examples/hybrid/schur_complement_W.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
Labels: Naming conventions

#786 more memory for TRMM
  .buildkite/longruns/pipeline.yml
Labels: Continuous integration :gear:

#788 Upgrade deps
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:
