Repository CliMA/ClimaAtmos.jl, pull requests merged in 2022-12, with the labels that each got.

#1175 Fix crashing case, add warning
  examples/hybrid/driver.jl
Labels: Logging :ledger:, bugfix :bug: :hammer:

#1177 Refactor ode init
  examples/hybrid/types.jl
Labels: Refactor

#1178 Fix stack traces
  examples/hybrid/driver.jl
Labels: bugfix :bug: :hammer:

#1184 Try removing call to get_inversion
  regression_tests/ref_counter.jl
  tc_driver/Surface.jl
Labels: Surface :surfer:

#1183 Add column plots back in
  examples/hybrid/classify_case.jl
  examples/hybrid/driver.jl
Labels: Visualization :art:

#1189 Remove some use of Ri_bulk_crit
  examples/hybrid/TurbulenceConvectionUtils.jl
  src/TurbulenceConvection/types.jl
  tc_driver/Cases.jl
  tc_driver/Surface.jl
Labels: Refactor, House cleaning :broom:

#1190 Refactor ODE initialization
  examples/hybrid/types.jl
Labels: Refactor

#1193 Refactor ode init
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
Labels: Refactor

#1197 Add debug info to precomputed quantities
  src/precomputed_quantities.jl
  src/thermo_state.jl
Labels: Debugging :mag::bug:

#1198 Bump minor version for new release
  Project.toml
Labels: Release

#1192 Refactor HS paper plots
  examples/hybrid/driver.jl
  post_processing/post_processing_funcs.jl
Labels: Refactor, Visualization :art:

#1200 Move try-catch to thermo_state function
  examples/hybrid/callbacks.jl
  post_processing/post_processing_funcs.jl
  src/precomputed_quantities.jl
  src/tendencies/implicit/implicit_tendency.jl
  src/tendencies/implicit/wfact.jl
  src/thermo_state.jl
Labels: Refactor, Debugging :mag::bug:

#1201 Update version of ClimaTimesteppers
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/types.jl
  ode_compat_examples/Manifest.toml
  ode_compat_examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  test/Project.toml
Labels: Refactor, Dependencies :spider_web:

#1204 Run long run trmm for shorter to see output
  .buildkite/longruns/pipeline.yml
Labels: Long runs :running_woman:

#1179 Update to new ClimaTimeSteppers
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
  ode_compat_examples/Manifest.toml
  ode_compat_examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  perf/benchmark.jl
  perf/flame.jl
  regression_tests/ref_counter.jl
  test/Project.toml
Labels: Time stepping :hourglass:

#1205 Remove remaining_tendency_increment
  examples/hybrid/staggered_nonhydrostatic_model.jl
Labels: House cleaning :broom:

#1206 Add debug statements for clims
  post_processing/define_tc_quicklook_profiles.jl
Labels: Debugging :mag::bug:

#1210 Update dependencies
  examples/Manifest.toml
  examples/Project.toml
  ode_compat_examples/Manifest.toml
  ode_compat_examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  test/Project.toml
Labels: Dependencies :spider_web:

#1215 Update DSS to DSS2
  examples/hybrid/callbacks.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  perf/flame.jl
  regression_tests/ref_counter.jl
  src/tendencies/hyperdiffusion.jl
Labels: Performance, Distributed

#1217 Update ClimaTimeSteppers compat and deps
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  ode_compat_examples/Manifest.toml
  ode_compat_examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  perf/flame.jl
  test/Project.toml
Labels: Dependencies :spider_web:

#1218 Add call to remap script for longrun job
  .buildkite/longruns/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  post_processing/remap/remap_helpers.jl
  post_processing/remap/remap_pipeline.jl
Labels: Visualization :art:, Automation :gear:

#1221 Time cache allocation
  examples/hybrid/driver.jl
Labels: Timing :stopwatch:

#1222 Try to fix longrun remapping
  examples/hybrid/driver.jl
Labels: Visualization :art:, Long runs :running_woman:

#1220 Upgrade deps
  docs/Manifest.toml
  examples/Manifest.toml
  ode_compat_examples/Manifest.toml
  perf/Manifest.toml
  perf/flame.jl
Labels: Dependencies :spider_web:

#1227 Refactor vert diff BL tend
  examples/hybrid/callbacks.jl
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
  src/model_getters.jl
  src/tendencies/vertical_diffusion_boundary_layer.jl
  src/types.jl
Labels: Refactor

#1228 Add and use ViscousSponge type
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
  src/model_getters.jl
  src/tendencies/viscous_sponge.jl
  src/types.jl
Labels: Refactor

#1230 Add and use RayleighSponge type
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
  src/model_getters.jl
  src/tendencies/implicit/implicit_tendency.jl
  src/tendencies/implicit/wfact.jl
  src/tendencies/rayleigh_sponge.jl
  src/types.jl
Labels: Refactor

#1232 Add docs cleanup GHA
  .github/workflows/DocCleanup.yml
Labels: Continuous integration :gear:
