Repository CliMA/ClimaAtmos.jl, pull requests merged in 2022-06, with the labels that each got.

#465 Add Nsight profiler to scaling pipeline.
  .buildkite/scaling/pipeline.yml
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/driver.jl
  examples/hybrid/plot_scaling_results.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  perf/Manifest.toml
  perf/Project.toml
Labels: Continuous integration :gear:, Performance monitoring :rocket: :mag:

#516 Upgrade to latest version of TurbulenceConvection
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/TCexample.jl
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/driver.jl
  examples/hybrid/parameter_set.jl
  examples/hybrid/types.jl
  perf/Manifest.toml
  perf/Project.toml
  post_processing/mse_tables.jl
Labels: Dependencies :spider_web:

#517 Swap axes in profile animations
  examples/hybrid/define_post_processing.jl
Labels: Visualization :art:

#519 Add low-resolution and high-resolution scaling tests
  .buildkite/scaling/pipeline.yml
  examples/hybrid/plot_scaling_results.jl
Labels: Continuous integration :gear:, Performance monitoring :rocket: :mag:

#521 Add NVTX ranges for dss calls and tendency functions.
  examples/Project.toml
  examples/hybrid/driver.jl
  examples/hybrid/hyperdiffusion.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  perf/Project.toml
Labels: Performance monitoring :rocket: :mag:

#526 Increase DSS overlap in Hyperdiffusion tendency
  examples/hybrid/hyperdiffusion.jl
Labels: Performance

#529 Prep for registering ClimaAtmos
  .github/workflows/CompatHelper.yml
  .github/workflows/TagBot.yml
  Project.toml
Labels: Release

#532 Add convenience function for script generation
  examples/hybrid/cli_options.jl
Labels: Workflow :gear: :ocean:

#533 Upgrade deps
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  perf/allocs.jl
Labels: Dependencies :spider_web:

#531 Upgrade deps, including latest TC version
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/parameter_set.jl
  perf/Manifest.toml
  perf/Project.toml
  perf/allocs.jl
  post_processing/mse_tables.jl
Labels: Dependencies :spider_web:

#539 Separate communication buffer for ᶜχρq_tot.
  .buildkite/pipeline.yml
  examples/hybrid/hyperdiffusion.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
Labels: Performance, bugfix :bug: :hammer:

#546 Upgrade deps
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/driver.jl
  perf/Manifest.toml
  perf/Project.toml
  post_processing/mse_tables.jl
Labels: Dependencies :spider_web:

#548 Use new way of handling clima parameters
  Project.toml
  docs/Manifest.toml
  docs/src/running_instructions.md
  examples/Manifest.toml
  examples/Project.toml
  examples/RRTMGPInterface.jl
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/define_post_processing.jl
  examples/hybrid/driver.jl
  examples/hybrid/parameter_set.jl
  examples/hybrid/radiation_utilities.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  parameters/create_parameters.jl
  perf/Manifest.toml
  perf/Project.toml
  post_processing/mse_tables.jl
  src/ClimaAtmos.jl
  src/Models/Models.jl
  src/Models/Nonhydrostatic2DModels/Nonhydrostatic2DModels.jl
  src/Models/Nonhydrostatic2DModels/equations_cache.jl
  src/Models/Nonhydrostatic2DModels/equations_precipitation.jl
  src/Models/Nonhydrostatic3DModels/Nonhydrostatic3DModels.jl
  src/Models/Nonhydrostatic3DModels/equations_base_model.jl
  src/Models/Nonhydrostatic3DModels/equations_gravitational_potential.jl
  src/Models/Nonhydrostatic3DModels/equations_pressure.jl
  src/Models/SingleColumnModels/SingleColumnModels.jl
  src/Models/SingleColumnModels/equations_base_model.jl
  src/Models/SingleColumnModels/equations_gravitational_potential.jl
  src/Models/SingleColumnModels/equations_pressure.jl
  src/Models/SingleColumnModels/equations_vertical_diffusion.jl
  src/Parameters.jl
  src/Utils/InitialConditions/InitialConditions.jl
  src/Utils/InitialConditions/init_1d_ekman_column.jl
  src/Utils/InitialConditions/init_2d_dry_bubble.jl
  src/Utils/InitialConditions/init_2d_moist_bubble.jl
  src/Utils/InitialConditions/init_2d_precipitating_bubble.jl
  src/Utils/InitialConditions/init_3d_baroclinic_wave.jl
  src/Utils/InitialConditions/init_3d_rising_bubble.jl
  src/Utils/InitialConditions/init_3d_solid_body_rotation.jl
  test/Project.toml
  test/runtests.jl
  test/test_cases/run_1d_ekman_column.jl
  test/test_cases/run_2d_dry_bubble.jl
  test/test_cases/run_2d_moist_bubble.jl
  test/test_cases/run_2d_precipitating_bubble.jl
  test/test_cases/run_3d_balanced_flow.jl
  test/test_cases/run_3d_baroclinic_wave.jl
  test/test_cases/run_3d_rising_bubble.jl
  test/test_cases/run_3d_solid_body_rotation.jl
  test/test_domains.jl
  test/test_models.jl
Labels: ClimaParameters :control_knobs:

#560 Fix `parsed_args_from_command_line_flags`
  examples/hybrid/cli_options.jl
Labels: bugfix :bug: :hammer:

#563 Define thermo_params in save_to_disk_func
  examples/hybrid/driver.jl
Labels: Long runs :running_woman:

#564 Slim deps, move doctests to docs
  docs/make.jl
  test/Project.toml
  test/runtests.jl
Labels: Dependencies :spider_web:, Tests

#571 Fix some variables that should be constant
  .buildkite/pipeline.yml
  examples/hybrid/driver.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
Labels: Performance

#573 Add JET script to perf folder
  perf/Project.toml
  perf/jet.jl
Labels: Performance monitoring :rocket: :mag:

#565 Update scaling pipeline.
  .buildkite/scaling/pipeline.yml
  .buildkite/scaling/sphere_held_suarez.sh
  examples/hybrid/plot_scaling_results.jl
Labels: Performance monitoring :rocket: :mag:
