Repository CliMA/ClimaAtmos.jl, pull requests merged in 2022-03, with the labels that each got.

#242 Update Project.toml
  Project.toml
  test/Project.toml
  test/test_cases/run_3d_rising_bubble.jl
Labels: ASAP

#228 Add bubble with moisture and precipitation model
  .buildkite/pipeline.yml
  Project.toml
  src/Models/Models.jl
  src/Models/Nonhydrostatic2DModels/Nonhydrostatic2DModels.jl
  src/Models/Nonhydrostatic2DModels/equations_base_model.jl
  src/Models/Nonhydrostatic2DModels/equations_gravitational_potential.jl
  src/Models/Nonhydrostatic2DModels/equations_moisture.jl
  src/Models/Nonhydrostatic2DModels/equations_pressure.jl
  src/Models/Nonhydrostatic2DModels/equations_thermodynamics.jl
  src/Models/Nonhydrostatic2DModels/nonhydrostatic_2d_model.jl
  src/Models/style_moisture.jl
  src/Models/style_precipitation.jl
  src/Utils/InitialConditions/InitialConditions.jl
  src/Utils/InitialConditions/init_2d_dry_bubble.jl
  src/Utils/InitialConditions/init_2d_moist_bubble.jl
  test/Project.toml
  test/test_cases/run_2d_dry_bubble.jl
  test/test_cases/run_2d_moist_bubble.jl
  test/test_models.jl
Labels: sprint

#254 Add png plotting callback
  src/Callbacks/callback.jl
  test/test_cases/run_2d_dry_bubble.jl
  test/test_cases/run_2d_moist_bubble.jl
Labels: Visualization :art:

#261 Update README.md
  README.md
Labels: bug

#252 Initial working example with cache
  src/Models/Models.jl
  src/Models/Nonhydrostatic2DModels/Nonhydrostatic2DModels.jl
  src/Models/Nonhydrostatic2DModels/default_ode_cache.jl
  src/Models/Nonhydrostatic2DModels/equations_base_model.jl
  src/Models/Nonhydrostatic2DModels/equations_cache.jl
  src/Models/Nonhydrostatic2DModels/equations_gravitational_potential.jl
  src/Models/Nonhydrostatic2DModels/equations_moisture.jl
  src/Models/Nonhydrostatic2DModels/equations_pressure.jl
  src/Models/Nonhydrostatic2DModels/equations_thermodynamics.jl
  src/Models/Nonhydrostatic2DModels/equations_vertical_diffusion.jl
  src/Models/Nonhydrostatic2DModels/nonhydrostatic_2d_model.jl
  src/Models/Nonhydrostatic3DModels/nonhydrostatic_3d_model.jl
  src/Models/SingleColumnModels/single_column_model.jl
  src/Models/style_cache.jl
  src/Simulations/Simulations.jl
  src/Simulations/simulation.jl
  test/Project.toml
  test/test_cases/run_2d_dry_bubble.jl
  test/test_cases/run_2d_moist_bubble.jl
  test/test_models.jl
Labels: sprint, design, Microphysics
