Repository CliMA/ClimaAtmos.jl, pull requests merged in 2022-02, with the labels that each got.

#202 Don't capture thermodynamic states
  src/Models/Nonhydrostatic2DModels/equations_pressure.jl
  src/Models/Nonhydrostatic3DModels/equations_pressure.jl
Labels: Refactor

#205 Add plots to artifacts
  .buildkite/pipeline.yml
  test/test_cases/run_1d_ekman_column.jl
  test/test_cases/run_2d_rising_bubble.jl
Labels: Visualization :art:

#207 Remove unnecessary deps
  Project.toml
  src/Simulations/Simulations.jl
  src/Simulations/simulation.jl
  test/Project.toml
Labels: Dependencies :spider_web:

#208 Reduce use of Global scope, use cache
  test/test_cases/run_1d_ekman_column.jl
Labels: Refactor

#209 Qualify methods and types more
  src/Models/SingleColumnModels/SingleColumnModels.jl
  src/Models/SingleColumnModels/single_column_model.jl
  test/test_cases/run_1d_ekman_column.jl
Labels: Refactor

#222 import ClimaCorePlots
  test/test_cases/run_2d_rising_bubble.jl
  test/test_cases/run_3d_balanced_flow.jl
  test/test_cases/run_3d_baroclinic_wave.jl
  test/test_cases/run_3d_rising_bubble.jl
  test/test_cases/run_3d_solid_body_rotation.jl
Labels: bug

#213 revamp scm
  src/Models/Models.jl
  src/Models/Nonhydrostatic2DModels/nonhydrostatic_2d_model.jl
  src/Models/Nonhydrostatic3DModels/nonhydrostatic_3d_model.jl
  src/Models/SingleColumnModels/SingleColumnModels.jl
  src/Models/SingleColumnModels/equations_base_model.jl
  src/Models/SingleColumnModels/equations_gravitational_potential.jl
  src/Models/SingleColumnModels/equations_moisture.jl
  src/Models/SingleColumnModels/equations_pressure.jl
  src/Models/SingleColumnModels/equations_thermodynamics.jl
  src/Models/SingleColumnModels/single_column_model.jl
  src/Models/style_base_model.jl
  src/Models/style_moisture.jl
  src/Models/style_thermodynamics.jl
  test/test_cases/run_1d_ekman_column.jl
  test/test_models.jl
Labels: sprint

#231 Add `turbconv` into `SingleColumnModel` and `ConstantViscosity`
  src/Models/Models.jl
  src/Models/SingleColumnModels/SingleColumnModels.jl
  src/Models/SingleColumnModels/equations_base_model.jl
  src/Models/SingleColumnModels/equations_thermodynamics.jl
  src/Models/SingleColumnModels/equations_turbconv.jl
  src/Models/SingleColumnModels/single_column_model.jl
  src/Models/style_turbconv.jl
  src/Simulations/simulation.jl
  test/test_cases/run_1d_ekman_column.jl
  test/test_models.jl
Labels: sprint, design

#233 Add ekman validation test
  .buildkite/pipeline.yml
  test/Project.toml
  test/test_cases/run_1d_ekman_column.jl
Labels: Continuous integration :gear:
