Repository CliMA/ClimaAtmos.jl, pull requests merged in 2022-07, with the labels that each got.

#575 Upgrade deps
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#578 Bump minor version
  Project.toml
Labels: Release

#595 Remove regression tests for trivially zero solutions
  post_processing/mse_tables.jl
Labels: Tests, bugfix :bug: :hammer:, Regression tests

#589 Centralize thermo state field dispatching
  examples/hybrid/define_post_processing.jl
  examples/hybrid/driver.jl
  examples/hybrid/radiation_utilities.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  examples/hybrid/thermo_state.jl
Labels: Thermodynamics :fire:

#592 Remove some global closures
  examples/hybrid/define_post_processing.jl
  examples/hybrid/driver.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  examples/hybrid/types.jl
Labels: Refactor

#597 Make running any job_id easy
  examples/hybrid/cli_options.jl
Labels: Workflow :gear: :ocean:

#602 Remove more closures
  examples/hybrid/callbacks.jl
  examples/hybrid/driver.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  examples/hybrid/types.jl
Labels: Refactor

#609 Update IntervalSets compat entry, upgrade deps
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#594 Print zeros in mse tables when ref counter is incremented
  post_processing/compute_mse.jl
  post_processing/print_new_mse.jl
  post_processing/self_reference_or_path.jl
Labels: Workflow :gear: :ocean:, Logic :brain:

#608 Move regression computations into function
  examples/hybrid/driver.jl
  post_processing/regression_tests.jl
Labels: Refactor

#615 Make get_simulation not depend on ArgParseSettings
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
Labels: Workflow :gear: :ocean:

#612 Rename post processing folder to `regression_tests`
  .buildkite/pipeline.yml
  examples/hybrid/driver.jl
  regression_tests/README.md
  regression_tests/compute_mse.jl
  regression_tests/move_output.jl
  regression_tests/mse_tables.jl
  regression_tests/print_new_mse.jl
  regression_tests/print_new_ref_counter.jl
  regression_tests/ref_counter.jl
  regression_tests/regression_tests.jl
  regression_tests/self_reference_or_path.jl
Labels: Regression tests

#625 Fix 623
  examples/hybrid/driver.jl
  examples/hybrid/utilities.jl
Labels: Performance

#622 Update regression readme
  regression_tests/README.md
Labels: documentation

#631 Fix post processing memory leaks
  examples/hybrid/define_post_processing.jl
Labels: bugfix :bug: :hammer:, Memory :brain:

#642 Declutter global scope
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
Labels: Refactor

#643 Move callbacks into function
  examples/hybrid/callbacks.jl
  examples/hybrid/driver.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  examples/hybrid/types.jl
Labels: Refactor

#645 Save to sol less frequently in long runs
  .buildkite/longruns/pipeline.yml
Labels: Long runs :running_woman:

#646 Add get_integrator function
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
Labels: Refactor

#639 Delete duplicate code
  examples/hybrid/define_post_processing.jl
Labels: House cleaning :broom:

#649 move θ_virt to assign_thermo_aux
  examples/hybrid/TurbulenceConvectionUtils.jl
  tc_driver/dycore.jl
Labels: Refactor

#653 Add perf target bk job, update benchmarks
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/utilities.jl
  perf/benchmark.jl
  perf/benchmark_utils.jl
  perf/flame.jl
Labels: Performance monitoring :rocket: :mag:

#660 Fix threading performance target
  .buildkite/pipeline.yml
Labels: Performance, bugfix :bug: :hammer:

#661 Upgrade deps
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#663 Use ClimaCore trunc field type printing
  examples/hybrid/driver.jl
  examples/hybrid/truncate_stack_traces.jl
Labels: Logging :ledger:

#669 Upload flame graph to GCP
  perf/flame.jl
Labels: Performance monitoring :rocket: :mag:

#674 Fix header name in perf summary table
  perf/tabulate_perf_summary.jl
Labels: Performance monitoring :rocket: :mag:

#676 Fix test infra for print zeros with ref ctr incrmnt
  regression_tests/print_new_mse.jl
Labels: bugfix :bug: :hammer:, Regression tests

#677 Improve log when missing functions
  perf/tabulate_perf_summary.jl
Labels: Performance monitoring :rocket: :mag:, Logging :ledger:

#680 Fix table perf percent change w strings
  perf/tabulate_perf_summary.jl
Labels: Performance monitoring :rocket: :mag:, bugfix :bug: :hammer:

#684 Bump minor version for new release
  Project.toml
Labels: Release

#689 Trim some duplicate code
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
Labels: Refactor

#692 Improve flame graph
  perf/flame.jl
Labels: Performance monitoring :rocket: :mag:

#693 Remove allocations in percentile_bounds_mean_norm
  regression_tests/mse_tables.jl
  src/TurbulenceConvection/utility_functions.jl
Labels: Performance

#698 Add assertion that job finishes
  examples/hybrid/driver.jl
Labels: Defensive programming :crossed_swords:

#695 Cache variables to avoid allocations
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
Labels: Refactor, Performance

#699 Add comments to perf script
  perf/benchmark.jl
  perf/jet.jl
Labels: Performance monitoring :rocket: :mag:

#682 Increase integration time for high resolution tests in scaling pipeline.
  .buildkite/comparison/README.md
  .buildkite/comparison/comparison_sphere_held_suarez.sh
  .buildkite/comparison/generate_comparison_pipeline.sh
  .buildkite/comparison/pipeline.yml
  .buildkite/scaling/pipeline.yml
  .buildkite/scaling/sphere_held_suarez.sh
  examples/hybrid/comparison_plots.jl
  examples/hybrid/plot_scaling_results.jl
Labels: Performance monitoring :rocket: :mag:

#704 Correct compats, test latest versions
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/callbacks.jl
  examples/hybrid/cli_options.jl
  examples/hybrid/types.jl
  perf/Manifest.toml
  perf/Project.toml
  test/Project.toml
  test/runtests.jl
Labels: Refactor, Dependencies :spider_web:, Tests

#706 Exercise test env in buildkite job
  .buildkite/pipeline.yml
  .github/workflows/ci.yml
  bors.toml
  test/runtests.jl
Labels: Continuous integration :gear:

#712 Try to fix flakey test env job
  .buildkite/pipeline.yml
Labels: Tests

#711 Upgrade deps
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  regression_tests/mse_tables.jl
Labels: Dependencies :spider_web:

#715 Adds Thomas algorithm for solving a tri-diagonal system of linear equations.
  examples/hybrid/schur_complement_W.jl
  regression_tests/mse_tables.jl
  test/runtests.jl
  test/test_thomas.jl
Labels: Performance

#716 Update filter for plotting scaling results
  examples/hybrid/plot_scaling_results.jl
Labels: Performance monitoring :rocket: :mag:, bugfix :bug: :hammer:
