Repository CliMA/ClimaAtmos.jl, pull requests merged in 2023-11, with the labels that each got.

#2338 Update github workflow for merge queue
  .github/workflows/CodeCov.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/julia_formatter.yml
  regression_tests/README.md
  regression_tests/move_output.jl
Labels: Launch Buildkite

#2337 change edmfx sgs mass flux to advect a*tracer
  config/default_configs/default_edmf_config.yml
  src/prognostic_equations/edmfx_sgs_flux.jl
  src/solver/type_getters.jl
  src/solver/types.jl
Labels: Launch Buildkite

#2339 update prognostic edmf cases in buildkite
  .buildkite/pipeline.yml
  config/model_configs/prognostic_edmfx_bomex_box.yml
  config/model_configs/prognostic_edmfx_bomex_column.yml
  config/model_configs/prognostic_edmfx_bomex_fixtke_box.yml
  config/model_configs/prognostic_edmfx_dycoms_rf01_box.yml
  config/model_configs/prognostic_edmfx_gabls_box.yml
  config/model_configs/prognostic_edmfx_gabls_tke_box.yml
  config/model_configs/prognostic_edmfx_gabls_tke_column.yml
  config/model_configs/prognostic_edmfx_rico_box.yml
  config/model_configs/prognostic_edmfx_rico_column.yml
  config/model_configs/prognostic_edmfx_trmm_column.yml
  toml/prognostic_edmfx_box.toml
  toml/prognostic_edmfx_dycoms_rf01_box.toml
Labels: Launch Buildkite

#2345 Update nsight-systems version
  .buildkite/comparison/pipeline.sh
  .buildkite/longruns/pipeline.yml
  .buildkite/scaling/pipeline.sh
Labels: Performance monitoring :rocket: :mag:, GPU

#2351 remove some regression tests
  .buildkite/pipeline.yml
  config/model_configs/single_column_nonorographic_gravity_wave.yml
  config/model_configs/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_res.yml
  config/model_configs/sphere_baroclinic_wave_rhoe.yml
  config/model_configs/sphere_held_suarez_rhoe_hightop.yml
  config/model_configs/sphere_held_suarez_rhotheta.yml
  config/model_configs/sphere_zalesak_upwind_tracer_energy_ssp_baroclinic_wave_rhoe_equilmoist.yml
  regression_tests/mse_tables.jl
  test/config.jl
Labels: Launch Buildkite

#2372 Add an empty 1-moment precipitation tendency
  .buildkite/pipeline.yml
  config/default_configs/default_config.yml
  config/model_configs/single_column_precipitation_test.yml
  config/model_configs/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_res.yml
  examples/hybrid/driver.jl
  post_processing/plot_single_column_precip.jl
  src/cache/precomputed_quantities.jl
  src/diagnostics/Diagnostics.jl
  src/diagnostics/core_diagnostics.jl
  src/initial_conditions/atmos_state.jl
  src/initial_conditions/initial_conditions.jl
  src/initial_conditions/local_state.jl
  src/parameterized_tendencies/microphysics/precipitation.jl
  src/parameters/create_parameters.jl
  src/prognostic_equations/implicit/implicit_solver.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/solver/type_getters.jl
  src/solver/types.jl
  toml/single_column_precipitation_test.toml
Labels: Microphysics

#2358 Update instantaneous zenith angle function
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  regression_tests/ref_counter.jl
  src/callbacks/callbacks.jl
Labels: Launch Buildkite

#2377 Use ClimaCore 0.11 and MPITrampoline
  .buildkite/JuliaProject.toml
  .buildkite/gpu_pipeline/pipeline.yml
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/scaling/pipeline.sh
  .dev/Manifest.toml
  Project.toml
  README.md
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#2383 Reduce memory footprint
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  src/parameterized_tendencies/radiation/RRTMGPInterface.jl
Labels: Launch Buildkite

#2388 Add annotations for flux calculation functions
  .buildkite/gpu_pipeline/pipeline.yml
  src/parameterized_tendencies/radiation/RRTMGPInterface.jl
Labels: Launch Buildkite

#2392 fix typo
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
Labels: Continuous integration :gear:

#2391 Tag `ClimaAtmos.jl` V0.17.0
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Launch Buildkite
