Repository CliMA/ClimaAtmos.jl, pull requests merged in 2023-05, with the labels that each got.

#1619 Add ArgParse to deps
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#1620 Move code into src
  docs/src/cl_args.jl
  docs/src/repl_scripts.jl
  examples/Manifest.toml
  examples/hybrid/driver.jl
  examples/hybrid/get_cache_and_tendency.jl
  examples/hybrid/get_callbacks.jl
  examples/hybrid/get_simulation_and_args_integrator.jl
  examples/ordinary_diff_eq_bug_fixes.jl
  perf/allocs.jl
  perf/benchmark.jl
  perf/config_parsed_args.jl
  src/ClimaAtmos.jl
  src/callbacks/callbacks.jl
  src/staggered_nonhydrostatic_model.jl
  src/tendencies/implicit/implicit_tendency.jl
  src/tendencies/remaining_tendency.jl
  src/utils/cli_options.jl
  src/utils/model_getters.jl
  src/utils/nvtx.jl
  src/utils/type_getters.jl
  test/parameter_tests.jl
Labels: Refactor

#1632 Fix race condition in ogwd tests
  test/orographic_gravity_wave/ogwd_3d.jl
  test/orographic_gravity_wave/ogwd_baseflux.jl
Labels: bug, bugfix :bug: :hammer:

#1635 Bump ClimaAtmos version
  Project.toml
Labels: Continuous integration :gear:, Release

#1634 Move more code into src
  .buildkite/pipeline.yml
  examples/hybrid/driver.jl
  perf/flame.jl
  src/ClimaAtmos.jl
  src/solve.jl
  src/staggered_nonhydrostatic_model.jl
  src/utils/type_getters.jl
  src/utils/utilities.jl
Labels: Refactor

#1636 Rename w to u_3
  post_processing/post_processing_funcs.jl
  post_processing/remap/remap_helpers.jl
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  src/InitialConditions/atmos_state.jl
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/TurbulenceConvection/update_aux.jl
  src/parameterizations/gravity_wave_drag/orographic_gravity_wave.jl
  src/parameterizations/sponge/viscous_sponge.jl
  src/precomputed_quantities.jl
  src/tendencies/advection.jl
  src/tendencies/hyperdiffusion.jl
  src/tendencies/implicit/implicit_tendency.jl
  src/tendencies/implicit/wfact.jl
  src/tendencies/zero_velocity.jl
  src/utils/abbreviations.jl
  src/utils/debug_utils.jl
  src/utils/discrete_hydrostatic_balance.jl
  src/utils/utilities.jl
  src/utils/variable_manipulations.jl
  test/implicit/wfact.jl
  test/orographic_gravity_wave/ogwd_3d.jl
  test/orographic_gravity_wave/ogwd_baseflux.jl
Labels: bikeshedding, Naming conventions

#1639 Allow for non-default keys in the parser
  .buildkite/pipeline.yml
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  src/utils/cli_options.jl
Labels: bugfix :bug: :hammer:

#1613 EDMFX entrainment/detrainment
  .buildkite/pipeline.yml
  perf/flame.jl
  src/ClimaAtmos.jl
  src/staggered_nonhydrostatic_model.jl
  src/tendencies/edmfx_closures.jl
  src/tendencies/remaining_tendency.jl
  src/tendencies/vertical_diffusion_boundary_layer.jl
  src/utils/cli_options.jl
  src/utils/type_getters.jl
  src/utils/types.jl
Labels: EDMF :tornado:

#1642 Ensure mse key entries are correct
  examples/hybrid/driver.jl
  regression_tests/regression_tests.jl
Labels: Continuous integration :gear:, Workflow :gear: :ocean:

#1643 Upgrade to latest ClimaCore, ClimaComms and ClimaCoreTempestRemap
  .dev/Manifest.toml
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/comms.jl
  examples/hybrid/driver.jl
  perf/Manifest.toml
  perf/Project.toml
  perf/flame.jl
  src/solve.jl
  src/staggered_nonhydrostatic_model.jl
  src/utils/type_getters.jl
  src/utils/utilities.jl
  test/Project.toml
Labels: Dependencies :spider_web:

#1645 use cached sfc_conditions
  .buildkite/pipeline.yml
  src/tendencies/edmfx_closures.jl
  src/tendencies/vertical_diffusion_boundary_layer.jl
Labels: EDMF :tornado:

#1651 Fix longrun allocation job
  perf/allocs.jl
Labels: Performance monitoring :rocket: :mag:

#1652 add edmfx advection on the sphere
  .buildkite/pipeline.yml
  src/InitialConditions/initial_conditions.jl
  src/utils/type_getters.jl
Labels: EDMF :tornado:

#1657 Update dependencies
  .dev/Manifest.toml
  Project.toml
  artifacts/download_artifacts.jl
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  src/callbacks/callbacks.jl
  src/parameterizations/radiation/radiation.jl
  test/Project.toml
Labels: Dependencies :spider_web:

#1668 Move from bors to GitHub Merge Queue
  .github/workflows/CodeCov.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/julia_formatter.yml
  bors.toml
  regression_tests/README.md
  regression_tests/move_output.jl
Labels: Launch Buildkite

#1669 Remove mention of bors in readme
  README.md
Labels: Launch Buildkite

#1672 Use first-order upwinding in Zalesak vertical transport jacobian
  .buildkite/pipeline.yml
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  src/tendencies/implicit/wfact.jl
Labels: Launch Buildkite

#1447 Unify surface parametrization of dycore and EDMF
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/toml/bomex.toml
  examples/hybrid/driver.jl
  perf/config_parsed_args.jl
  perf/flame.jl
  post_processing/remap/remap_helpers.jl
  regression_tests/ref_counter.jl
  src/ClimaAtmos.jl
  src/InitialConditions/initial_conditions.jl
  src/SurfaceStates/SurfaceStates.jl
  src/SurfaceStates/surface_conditions.jl
  src/SurfaceStates/surface_setups.jl
  src/SurfaceStates/surface_state.jl
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/TurbulenceConvection/turbulence_functions.jl
  src/TurbulenceConvection/types.jl
  src/TurbulenceConvection/update_aux.jl
  src/callbacks/callbacks.jl
  src/dycore_equations/sgs_flux_tendencies.jl
  src/parameterizations/TurbulenceConvection/tc_functions.jl
  src/parameterizations/held_suarez/held_suarez.jl
  src/parameterizations/radiation/radiation.jl
  src/precomputed_quantities.jl
  src/staggered_nonhydrostatic_model.jl
  src/tendencies/edmfx_closures.jl
  src/tendencies/remaining_tendency.jl
  src/tendencies/vertical_diffusion_boundary_layer.jl
  src/utils/abbreviations.jl
  src/utils/classify_case.jl
  src/utils/cli_options.jl
  src/utils/model_getters.jl
  src/utils/surface.jl
  src/utils/type_getters.jl
  src/utils/types.jl
Labels: EDMF :tornado:, Launch Buildkite

#1681 Update parsed_args_per_job_id comment
  src/utils/cli_options.jl
Labels: Workflow :gear: :ocean:, Launch Buildkite

#1677 Add documentation for orographic gravity wave
  docs/bibliography.bib
  docs/make.jl
  docs/src/gravity_wave.md
Labels: documentation, Launch Buildkite

#1624 Add surface elevation spectra to buildkite CI outputs
  .buildkite/pipeline.yml
  post_processing/plot/plot_helpers.jl
  post_processing/plot/plot_pipeline.jl
  post_processing/remap/remap_helpers.jl
Labels: Launch Buildkite

#1680 Rename dss! -> dss_op! in loop, update weighted_dss ops.
  src/tendencies/hyperdiffusion.jl
Labels: Launch Buildkite

#1692 Fix exchange coefficient expression in vertical diffusion tendency.
  src/tendencies/vertical_diffusion_boundary_layer.jl
Labels: Launch Buildkite

#1660 Fix topography bugs in implicit solver
  .buildkite/longruns/pipeline.yml
  regression_tests/ref_counter.jl
  src/staggered_nonhydrostatic_model.jl
  src/tendencies/implicit/wfact.jl
  src/utils/type_getters.jl
  test/implicit/wfact.jl
Labels: Launch Buildkite

#1696 Fix repl scripts and lower allocation limits
  perf/flame.jl
  src/utils/cli_options.jl
  src/utils/yaml_helper.jl
Labels: bugfix :bug: :hammer:, Launch Buildkite

#1678 Update dependencies
  .dev/Manifest.toml
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  src/parameterizations/radiation/radiation.jl
  src/utils/utilities.jl
  test/Project.toml
Labels: Dependencies :spider_web:, Launch Buildkite

#1698 Add CUDA with compat, update deps
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  perf/jet_nfailures.jl
  regression_tests/ref_counter.jl
  src/utils/utilities.jl
  test/Project.toml
Labels: Dependencies :spider_web:, Launch Buildkite

#1703 Update to latest ClimaCore
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  src/solve.jl
  src/staggered_nonhydrostatic_model.jl
  src/utils/utilities.jl
Labels: GPU, Launch Buildkite

#1702 Fix conditional_assign! allocations
  perf/flame.jl
  src/TurbulenceConvection/utility_functions.jl
Labels: Launch Buildkite

#1705 Bump patch version
  Project.toml
Labels: Launch Buildkite

#1707 renaming folders in src
  src/ClimaAtmos.jl
  src/parameterized_tendencies/TurbulenceConvection/tc_functions.jl
  src/parameterized_tendencies/gravity_wave_drag/non_orographic_gravity_wave.jl
  src/parameterized_tendencies/gravity_wave_drag/orographic_gravity_wave.jl
  src/parameterized_tendencies/gravity_wave_drag/orographic_gravity_wave_helper.jl
  src/parameterized_tendencies/held_suarez/held_suarez.jl
  src/parameterized_tendencies/microphysics/precipitation.jl
  src/parameterized_tendencies/radiation/RRTMGPInterface.jl
  src/parameterized_tendencies/radiation/radiation.jl
  src/parameterized_tendencies/radiation/radiation_utilities.jl
  src/parameterized_tendencies/sponge/rayleigh_sponge.jl
  src/parameterized_tendencies/sponge/viscous_sponge.jl
  src/prognostic_equations/advection.jl
  src/prognostic_equations/edmf_coriolis.jl
  src/prognostic_equations/edmfx_closures.jl
  src/prognostic_equations/forcing/large_scale_advection.jl
  src/prognostic_equations/forcing/subsidence.jl
  src/prognostic_equations/hyperdiffusion.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/prognostic_equations/implicit/schur_complement_W.jl
  src/prognostic_equations/implicit/wfact.jl
  src/prognostic_equations/pressure_work.jl
  src/prognostic_equations/remaining_tendency.jl
  src/prognostic_equations/vertical_diffusion_boundary_layer.jl
  src/prognostic_equations/zero_velocity.jl
Labels: Consistency :dart:, Launch Buildkite

#1710 Update dependencies
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:, Launch Buildkite

#1693 Add simple gpu example
  .buildkite/pipeline.yml
  examples/hybrid/driver.jl
  src/staggered_nonhydrostatic_model.jl
  src/utils/cli_options.jl
  src/utils/common_spaces.jl
  src/utils/type_getters.jl
Labels: Launch Buildkite

#1711 Revert "Move from bors to GitHub Merge Queue"
  .github/workflows/CodeCov.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/julia_formatter.yml
  bors.toml
  regression_tests/README.md
  regression_tests/move_output.jl
Labels: Workflow :gear: :ocean:

#1713 Refactor driver for performance benchmark
  .buildkite/pipeline.yml
  examples/hybrid/driver.jl
  examples/hybrid/parameter_set.jl
  perf/allocs_per_case.jl
  perf/benchmark.jl
  perf/benchmark_step.jl
  perf/config_parsed_args.jl
  perf/flame.jl
  perf/inference_flame_init.jl
  perf/jet.jl
  perf/jet_nfailures.jl
  post_processing/post_processing_funcs.jl
  regression_tests/ref_counter.jl
  src/ClimaAtmos.jl
  src/create_parameters.jl
  src/solve.jl
  src/utils/type_getters.jl
  src/utils/types.jl
Labels: Refactor

#1721 Refactoring of files and folder structure in src
  docs/src/cl_args.jl
  docs/src/repl_scripts.jl
  perf/tabulate_perf_summary.jl
  post_processing/remap/remap_helpers.jl
  src/ClimaAtmos.jl
  src/TurbulenceConvection_deprecated/EDMF_functions.jl
  src/TurbulenceConvection_deprecated/Fields.jl
  src/TurbulenceConvection_deprecated/Grid.jl
  src/TurbulenceConvection_deprecated/Operators.jl
  src/TurbulenceConvection_deprecated/Parameters.jl
  src/TurbulenceConvection_deprecated/TurbulenceConvection.jl
  src/TurbulenceConvection_deprecated/closures/buoyancy_gradients.jl
  src/TurbulenceConvection_deprecated/closures/entr_detr.jl
  src/TurbulenceConvection_deprecated/closures/microphysics.jl
  src/TurbulenceConvection_deprecated/closures/mixing_length.jl
  src/TurbulenceConvection_deprecated/closures/perturbation_pressure.jl
  src/TurbulenceConvection_deprecated/dycore_api.jl
  src/TurbulenceConvection_deprecated/thermodynamics.jl
  src/TurbulenceConvection_deprecated/turbulence_functions.jl
  src/TurbulenceConvection_deprecated/types.jl
  src/TurbulenceConvection_deprecated/update_aux.jl
  src/TurbulenceConvection_deprecated/utility_functions.jl
  src/TurbulenceConvection_deprecated/variables.jl
  src/cache/cache.jl
  src/cache/precomputed_quantities.jl
  src/cache/temporary_quantities.jl
  src/dycore_equations_deprecated/sgs_flux_tendencies.jl
  src/initial_conditions/InitialConditions.jl
  src/initial_conditions/atmos_state.jl
  src/initial_conditions/initial_conditions.jl
  src/initial_conditions/local_state.jl
  src/parameterized_tendencies/radiation/held_suarez.jl
  src/parameterized_tendencies/turbulence_convection/tc_functions.jl
  src/parameters/Parameters.jl
  src/parameters/create_parameters.jl
  src/prognostic_equations/dss.jl
  src/prognostic_equations/limited_tendencies.jl
  src/solver/cli_options.jl
  src/solver/model_getters.jl
  src/solver/solve.jl
  src/solver/type_getters.jl
  src/solver/types.jl
  src/solver/yaml_helper.jl
  src/surface_conditions/SurfaceConditions.jl
  src/surface_conditions/surface_conditions.jl
  src/surface_conditions/surface_setups.jl
  src/surface_conditions/surface_state.jl
  src/topography/topography.jl
Labels: Consistency :dart:, Launch Buildkite

#1689 Add vertical integral for diagnostic EDMFX
  .buildkite/pipeline.yml
  examples/hybrid/driver.jl
  perf/flame.jl
  post_processing/contours_and_profiles.jl
  src/cache/precomputed_quantities.jl
  src/cache/temporary_quantities.jl
  src/callbacks/callbacks.jl
  src/initial_conditions/InitialConditions.jl
  src/initial_conditions/atmos_state.jl
  src/prognostic_equations/advection.jl
  src/prognostic_equations/hyperdiffusion.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/prognostic_equations/limited_tendencies.jl
  src/prognostic_equations/zero_velocity.jl
  src/solver/model_getters.jl
  src/solver/types.jl
Labels: EDMF :tornado:, Launch Buildkite
