Repository CliMA/ClimaAtmos.jl, pull requests merged in 2023-07, with the labels that each got.

#1852 Update manifest files, use ClimaCore's `column_thomas_solve!`
  .buildkite/pipeline.yml
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  perf/flame.jl
  perf/jet_test_nfailures.jl
  src/prognostic_equations/implicit/schur_complement_W.jl
  test/test_thomas.jl
Labels: Dependencies :spider_web:

#1850 Refactor callbacks, define `cycle!`
  examples/hybrid/driver.jl
  perf/flame.jl
  src/callbacks/callback_helpers.jl
  src/callbacks/callbacks.jl
  src/solver/solve.jl
  src/solver/type_getters.jl
  src/solver/types.jl
Labels: Performance monitoring :rocket: :mag:

#1858 Update installation instructions + landing page for Docs
  README.md
  docs/src/index.md
  docs/src/installation_instructions.md
Labels: documentation

#1857 Add function to call callbacks and precompile
  perf/flame.jl
  src/solver/solve.jl
Labels: Performance monitoring :rocket: :mag:

#1866 Remove unused argument
  src/solver/type_getters.jl
Labels: Refactor, House cleaning :broom:

#1872 Remove some jobs, improve some names
  .buildkite/pipeline.yml
  perf/benchmark.jl
  perf/benchmark_step.jl
  perf/flame.jl
  perf/inference_flame_init.jl
  perf/jet_test_nfailures.jl
  src/solver/solve.jl
  src/solver/types.jl
Labels: Performance monitoring :rocket: :mag:, GPU

#1867 Dont use AtmosTargetParsedArgs in gpu perf scripts
  .buildkite/pipeline.yml
  perf/benchmark_dump.jl
  perf/benchmark_step.jl
Labels: Performance monitoring :rocket: :mag:

#1878 Add auto-device option
  .buildkite/pipeline.yml
  src/solver/cli_options.jl
  src/solver/type_getters.jl
Labels: Interface

#1883 Update manifest files
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#1885 Fix leaky tests
  test/runtests.jl
Labels: Tests

#1886 Remove FieldFromNamedTuple
  src/TurbulenceConvection_deprecated/Fields.jl
  src/dycore_equations_deprecated/sgs_flux_tendencies.jl
  src/parameterized_tendencies/gravity_wave_drag/orographic_gravity_wave_helper.jl
  src/prognostic_equations/implicit/schur_complement_W.jl
Labels: Refactor

#1891 add mixing length to diagnostic edmf
  perf/flame.jl
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/precomputed_quantities.jl
  src/prognostic_equations/edmfx_sgs_flux.jl
Labels: EDMF :tornado:

#1910 Update manifest files
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/edmf_precomputed_quantities.jl
  src/callbacks/callbacks.jl
  src/parameterized_tendencies/gravity_wave_drag/non_orographic_gravity_wave.jl
  src/parameterized_tendencies/microphysics/precipitation.jl
  src/parameterized_tendencies/radiation/radiation.jl
  src/prognostic_equations/cloud_fraction.jl
  test/non_orographic_gravity_wave/nogw_test_mima.jl
Labels: Dependencies :spider_web:

#1913 Refactor quad loop
  src/prognostic_equations/cloud_fraction.jl
Labels: Refactor
