Repository CliMA/ClimaAtmos.jl, pull requests merged in 2023-03, with the labels that each got.

#1407 Remove incorrect anelastic option
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
  examples/hybrid/types.jl
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/model_getters.jl
  src/thermo_state.jl
  src/types.jl
Labels: EDMF :tornado:

#1327 Unify initial conditions of dycore and EDMF
  .buildkite/pipeline.yml
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/callbacks.jl
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
  post_processing/remap/remap_helpers.jl
  regression_tests/ref_counter.jl
  src/ClimaAtmos.jl
  src/InitialConditions/InitialConditions.jl
  src/InitialConditions/atmos_state.jl
  src/InitialConditions/baro_wave.jl
  src/InitialConditions/box.jl
  src/InitialConditions/initial_conditions.jl
  src/InitialConditions/local_state.jl
  src/InitialConditions/single_column.jl
  src/InitialConditions/sphere.jl
  src/TurbulenceConvection/variables.jl
  src/discrete_hydrostatic_balance.jl
  src/ref_state.jl
  src/tendencies/vertical_diffusion_boundary_layer.jl
  tc_driver/Cases.jl
  tc_driver/dycore.jl
Labels: EDMF :tornado:

#1412 Removing quadratures, (co)variances and third moment diagnostics
  examples/hybrid/callbacks.jl
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
  parameters/create_parameters.jl
  post_processing/define_tc_quicklook_profiles.jl
  src/InitialConditions/atmos_state.jl
  src/InitialConditions/local_state.jl
  src/TurbulenceConvection/EDMF_Environment.jl
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/types.jl
  src/TurbulenceConvection/update_aux.jl
  src/TurbulenceConvection/variables.jl
  src/model_getters.jl
  tc_driver/dycore_variables.jl
Labels: EDMF :tornado:

#1457 add mono option to post-processing remap
  examples/hybrid/orographic_gravity_wave_helper.jl
  post_processing/remap/remap_helpers.jl
Labels: enhancement

#1453 Align vertical_diffusion_boundary_layer_tendency with design docs
  perf/flame.jl
  regression_tests/ref_counter.jl
  src/callbacks.jl
  src/tendencies/vertical_diffusion_boundary_layer.jl
Labels: EDMF :tornado:

#1409 Add arg parsing for a TOML file, unify with parsed_args
  .buildkite/pipeline.yml
  .buildkite/toml/bomex.toml
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/parameter_set.jl
  parameters/create_parameters.jl
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  test/parameter_tests.jl
  test/parameter_tests.toml
Labels: ClimaParameters :control_knobs:, EDMF :tornado:

#1443 Add documentation for EDMF equations
  docs/make.jl
  docs/src/edmf_equations.md
Labels: EDMF :tornado:

#1439 test cnst_entr_pi_detr for all scm cases
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  regression_tests/ref_counter.jl
  src/TurbulenceConvection/closures/entr_detr.jl
  src/TurbulenceConvection/types.jl
  src/TurbulenceConvection/update_aux.jl
Labels: EDMF :tornado:

#1474 delete obsolete cases, cleanup in names
  .buildkite/pipeline.yml
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
Labels: EDMF :tornado:

#1475 remove ARM updrafts from regression
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
Labels: EDMF :tornado:

#1470 Add Bomex box experiment
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  post_processing/post_processing_funcs.jl
  src/InitialConditions/atmos_state.jl
  src/utils/classify_case.jl
  src/utils/type_getters.jl
Labels: EDMF :tornado:

#1469 Remove duplicated code
  examples/hybrid/get_cache_and_tendency.jl
  perf/flame.jl
  src/precomputed_quantities.jl
  src/tendencies/implicit/implicit_tendency.jl
  src/tendencies/implicit/wfact.jl
Labels: bugfix :bug: :hammer:, Dycore equations

#1479 Delete entr/detr from cache
  regression_tests/ref_counter.jl
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/closures/entr_detr.jl
  src/TurbulenceConvection/update_aux.jl
  src/TurbulenceConvection/variables.jl
Labels: EDMF :tornado:

#1486 Prescribe TKE for EDMF SCM cases
  .buildkite/pipeline.yml
  examples/Manifest.toml
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  src/InitialConditions/initial_conditions.jl
  src/TurbulenceConvection/EDMF_functions.jl
Labels: EDMF :tornado:

#1495 Delete (tmp) env tke related cached variables
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/dycore_api.jl
  src/TurbulenceConvection/update_aux.jl
  src/TurbulenceConvection/variables.jl
Labels: EDMF :tornado:

#1499 Unify precomputed quantities, clean up diagnostics
  examples/hybrid/driver.jl
  examples/hybrid/get_cache_and_tendency.jl
  examples/hybrid/get_callbacks.jl
  post_processing/post_processing_funcs.jl
  post_processing/remap/remap_helpers.jl
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  src/ClimaAtmos.jl
  src/callbacks/callbacks.jl
  src/parameterizations/radiation/radiation.jl
  src/precomputed_quantities.jl
  src/staggered_nonhydrostatic_model.jl
  src/tendencies/advection.jl
  src/tendencies/implicit/implicit_tendency.jl
  src/tendencies/implicit/wfact.jl
  src/utils/model_getters.jl
  src/utils/thermo_state.jl
  src/utils/type_getters.jl
  src/utils/types.jl
Labels: EDMF :tornado:

#1497 Remove buoyancy hack
  post_processing/define_tc_quicklook_profiles.jl
  regression_tests/ref_counter.jl
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/closures/perturbation_pressure.jl
  src/TurbulenceConvection/update_aux.jl
  src/TurbulenceConvection/variables.jl
  src/callbacks/callbacks.jl
  tc_driver/dycore_variables.jl
Labels: EDMF :tornado:

#1509 Lower perf limits
  perf/flame.jl
Labels: Tests, Performance

#1510 Longruns SSP: Use max_newton_iters 3
  .buildkite/longruns/pipeline.yml
Labels: Continuous integration :gear:

#1482 Add EDMFX model without tendencies and add new post-processing
  .buildkite/pipeline.yml
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/get_callbacks.jl
  perf/flame.jl
  post_processing/contours_and_profiles.jl
  src/InitialConditions/InitialConditions.jl
  src/InitialConditions/atmos_state.jl
  src/InitialConditions/initial_conditions.jl
  src/InitialConditions/local_state.jl
  src/callbacks/callbacks.jl
  src/parameterizations/microphysics/precipitation.jl
  src/precomputed_quantities.jl
  src/staggered_nonhydrostatic_model.jl
  src/tendencies/implicit/schur_complement_W.jl
  src/utils/model_getters.jl
  src/utils/type_getters.jl
  src/utils/types.jl
  src/utils/utilities.jl
Labels: EDMF :tornado:

#1515 Lower limit of n-jet failures
  perf/jet_nfailures.jl
Labels: Performance monitoring :rocket: :mag:

#1517 Update dependencies
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  ode_compat_examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#1518 Remove some loops over vertical column
  src/TurbulenceConvection/EDMF_Environment.jl
  src/TurbulenceConvection/EDMF_Updrafts.jl
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/TurbulenceConvection/types.jl
  src/TurbulenceConvection/variables.jl
Labels: Refactor

#1520 Add support to upwind density
  examples/hybrid/cli_options.jl
  src/staggered_nonhydrostatic_model.jl
  src/tendencies/implicit/implicit_tendency.jl
  src/utils/type_getters.jl
Labels: enhancement, Dycore equations
