Repository CliMA/ClimaAtmos.jl, pull requests merged in 2023-10, with the labels that each got.

#2182 Add DiffEqBase dependency
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  src/solver/type_getters.jl
  test/Project.toml
Labels: Dependencies :spider_web:

#2187 Upgrade to latest ClimaTimSteppers, minimally call `set_precomputed_quantities!`
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  perf/flame.jl
  src/ClimaAtmos.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/prognostic_equations/implicit/wfact.jl
  src/prognostic_equations/limited_tendencies.jl
  src/solver/type_getters.jl
  src/time_stepper/imex_ark.jl
  src/time_stepper/time_stepper.jl
Labels: Performance

#2190 Fix moist gpu example failure for mixed spaces expression
  src/prognostic_equations/vertical_diffusion_boundary_layer.jl
Labels: GPU

#2194 Update dependencies
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#2201 Fix CUDA compat, upgrade deps
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  regression_tests/ref_counter.jl
Labels: Dependencies :spider_web:

#2073 Config files for multi-year, high-topped atmosphere simulation with clearksy radiation
  .buildkite/longruns/pipeline.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky_tvinsolation.yml
  toml/longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky.toml
Labels: Long runs :running_woman:

#2202 Lower allocation limits
  perf/flame.jl
Labels: Performance tests

#2135 Ignore HDF5 in JET reports
  docs/Manifest.toml
  examples/Manifest.toml
  examples/hybrid/driver.jl
  perf/Manifest.toml
  perf/Project.toml
  perf/benchmark.jl
  perf/flame.jl
  perf/jet_report_nfailures.jl
  perf/jet_test_nfailures.jl
Labels: Performance monitoring :rocket: :mag:

#2206 Remove dss callback
  src/callbacks/callbacks.jl
  src/solver/type_getters.jl
Labels: House cleaning :broom:

#2208 Fix hardcoded paths in parameter tests
  test/parameter_tests.jl
Labels: Tests, bugfix :bug: :hammer:

#2211 Fix some type piracy
  src/TurbulenceConvection_deprecated/EDMF_functions.jl
  src/TurbulenceConvection_deprecated/Fields.jl
  src/TurbulenceConvection_deprecated/update_aux.jl
  src/cache/precomputed_quantities.jl
Labels: Latency

#2204 Remove temporary time stepper components
  src/time_stepper/hc_ars343.jl
  src/time_stepper/imex_ssprk.jl
Labels: House cleaning :broom:

#2214 Add function barrier across `sgs_explicit_tendency!`
  perf/flame.jl
  src/dycore_equations_deprecated/sgs_flux_tendencies.jl
Labels: Allocations

#2209 add constant detrainment option
  config/default_configs/default_edmf_config.yml
  src/parameters/Parameters.jl
  src/prognostic_equations/edmfx_entr_detr.jl
  src/solver/model_getters.jl
  src/solver/types.jl
Labels: EDMF :tornado:

#2218 Update CUDA - take 2
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#2227 Update compats and deps
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
Labels: Dependencies :spider_web:

#2239 Upgrade ClimaCore
  .dev/Manifest.toml
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#2254 Remove EDMFX and rename AdvectiveEDMFX to PrognosticEDMFX
  .buildkite/pipeline.yml
  config/default_configs/default_edmf_config.yml
  config/model_configs/advective_edmfx_adv_test_box.yml
  config/model_configs/advective_edmfx_bomex_box.yml
  config/model_configs/advective_edmfx_dycoms_rf01_box.yml
  config/model_configs/advective_edmfx_trmm_box.yml
  config/model_configs/edmfx_adv_test_sphere.yml
  config/model_configs/edmfx_bomex_box.yml
  config/model_configs/edmfx_gabls_box.yml
  config/model_configs/edmfx_rico_box.yml
  config/model_configs/prognostic_edmfx_adv_test_box.yml
  config/model_configs/prognostic_edmfx_bomex_box.yml
  config/model_configs/prognostic_edmfx_dycoms_rf01_box.yml
  config/model_configs/prognostic_edmfx_gabls_box.yml
  config/model_configs/prognostic_edmfx_rico_box.yml
  config/model_configs/prognostic_edmfx_trmm_box.yml
  config/perf_configs/flame_perf_target_edmfx.yml
  examples/hybrid/driver.jl
  perf/flame.jl
  src/ClimaAtmos.jl
  src/cache/edmf_precomputed_quantities.jl
  src/cache/precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/callbacks/callbacks.jl
  src/diagnostics/Diagnostics.jl
  src/diagnostics/default_diagnostics.jl
  src/diagnostics/edmfx_diagnostics.jl
  src/initial_conditions/InitialConditions.jl
  src/initial_conditions/atmos_state.jl
  src/prognostic_equations/advection.jl
  src/prognostic_equations/edmfx_closures.jl
  src/prognostic_equations/edmfx_entr_detr.jl
  src/prognostic_equations/edmfx_sgs_flux.jl
  src/prognostic_equations/hyperdiffusion.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/prognostic_equations/limited_tendencies.jl
  src/prognostic_equations/pressure_work.jl
  src/prognostic_equations/zero_velocity.jl
  src/solver/model_getters.jl
  src/solver/types.jl
  src/utils/variable_manipulations.jl
  toml/edmfx_box.toml
  toml/prognostic_edmfx_box.toml
  toml/prognostic_edmfx_box_advection.toml
Labels: EDMF :tornado:

#2261 Use SurfaceFluxes.jl v0.8.0
  .buildkite/longruns/pipeline.yml
  Project.toml
  config/longrun_configs/longrun_aquaplanet_amip.yml
  config/longrun_configs/longrun_aquaplanet_dyamond.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_clearsky_highres_hightop_rayleigh35e3_ft32.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_highres_allsky_ft32.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_highres_clearsky_ft32_earth.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky_tvinsolation.yml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  regression_tests/ref_counter.jl
  src/surface_conditions/surface_conditions.jl
  test/coupler_compatibility.jl
Labels: enhancement, Long runs :running_woman:

#2259 Clean up: remove underused quantities
  perf/benchmark_dump.jl
  perf/benchmark_step.jl
  src/cache/cache.jl
  src/callbacks/callbacks.jl
  src/diagnostics/writers.jl
  src/parameterized_tendencies/gravity_wave_drag/non_orographic_gravity_wave.jl
  src/prognostic_equations/cloud_fraction.jl
  src/prognostic_equations/forcing/subsidence.jl
  src/solver/type_getters.jl
Labels: House cleaning :broom:

#2279 Update dependencies, use ClimaCore operators
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  src/parameterized_tendencies/radiation/indefinite_integral_and_mapreduce.jl
  src/parameterized_tendencies/radiation/radiation.jl
Labels: Dependencies :spider_web:

#2183 Remove dependence on OrdinaryDiffEq
  Project.toml
  config/default_configs/default_config.yml
  docs/src/api.md
  regression_tests/ref_counter.jl
  src/callbacks/callbacks.jl
  src/dycore_equations_deprecated/sgs_flux_tendencies.jl
  src/initial_conditions/InitialConditions.jl
  src/initial_conditions/initial_conditions.jl
  src/parameterized_tendencies/radiation/radiation.jl
  src/prognostic_equations/implicit/implicit_solver.jl
  src/solver/solve.jl
  src/solver/type_getters.jl
Labels: Dependencies :spider_web:

#2274 separate precomputed quantities in 3 funcs
  src/cache/precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
Labels: EDMF :tornado:

#2286 Separate diagnostic edmf precomputed quants int 4 funcs
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/precomputed_quantities.jl
Labels: bikeshedding, EDMF :tornado:

#2281 Cache: clean up viscous and rayleigh
  src/cache/cache.jl
  src/cache/temporary_quantities.jl
  src/parameterized_tendencies/sponge/rayleigh_sponge.jl
  src/parameterized_tendencies/sponge/viscous_sponge.jl
  src/prognostic_equations/edmfx_sgs_flux.jl
  src/prognostic_equations/implicit/implicit_solver.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
Labels: House cleaning :broom:, Consistency :dart:

#2262 add prognostic tke equation for prognostic edmf
  .buildkite/pipeline.yml
  config/model_configs/prognostic_edmfx_bomex_tke_box.yml
  config/model_configs/prognostic_edmfx_gabls_tke_box.yml
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/prognostic_equations/edmfx_closures.jl
  src/prognostic_equations/edmfx_tke.jl
Labels: EDMF :tornado:

#2301 Add barowave jfnk flame graph
  .buildkite/pipeline.yml
  config/perf_configs/flame_sphere_baroclinic_wave_rhoe_equilmoist_expvdiff.yml
  perf/flame.jl
Labels: Performance monitoring :rocket: :mag:

#2302 Delete old TC params struct
  docs/src/api.md
  src/ClimaAtmos.jl
  src/TurbulenceConvection/Parameters.jl
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/initial_conditions/InitialConditions.jl
  src/parameters/Parameters.jl
  src/parameters/create_parameters.jl
  src/prognostic_equations/edmfx_closures.jl
  src/prognostic_equations/edmfx_entr_detr.jl
  src/prognostic_equations/edmfx_tke.jl
  src/surface_conditions/SurfaceConditions.jl
Labels: ClimaParameters :control_knobs:, EDMF :tornado:

#2297 Remove JLD2 as direct dependency
  .dev/Manifest.toml
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/hybrid/driver.jl
  perf/Manifest.toml
  post_processing/common_utils.jl
  src/ClimaAtmos.jl
  src/utils/classify_case.jl
  src/utils/utilities.jl
Labels: Dependencies :spider_web:

#2283 Remove CUDA as direct dependency
  .buildkite/pipeline.yml
  .gitignore
  Project.toml
  cuda_env/Project.toml
  docs/Manifest.toml
  docs/Project.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  test/Project.toml
Labels: Dependencies :spider_web:
