Repository CliMA/ClimaAtmos.jl, pull requests merged in 2023-09, with the labels that each got.

#2049 Precompute has_condensate
  src/prognostic_equations/cloud_fraction.jl
Labels: Performance

#2056 Explicit specification of time limits for newly added jobs
  .buildkite/longruns/pipeline.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_clearsky_highres_hightop_rayleigh35e3_ft64.yml
Labels: Long runs :running_woman:, bugfix :bug: :hammer:

#2057 Update deps
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#2062 Remove ReportMetrics.jl dep
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  perf/invalidations.jl
  test/Project.toml
Labels: Dependencies :spider_web:

#2071 Lower jet inference limit
  perf/jet_test_nfailures.jl
Labels: Performance tests

#2053 trying to get rid of MSLP overwrite
  examples/hybrid/driver.jl
  regression_tests/ref_counter.jl
  src/initial_conditions/initial_conditions.jl
  src/parameterized_tendencies/radiation/held_suarez.jl
  src/parameters/create_parameters.jl
  src/prognostic_equations/implicit/wfact.jl
Labels: ClimaParameters :control_knobs:

#2069 Adds env var for job name per buildkite step
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_clearsky_highres_hightop_rayleigh35e3_ft64.yml
  config/longrun_configs/longrun_hs_rhoe_dry_nz63_55km_rs35km.yml
  toml/longrun_aquaplanet_rhoe_equil_clearsky_highres_hightop_rayleigh35e3_ft64.toml
  toml/longrun_hs_rhoe_dry_nz63_55km_rs35km.toml
Labels: House cleaning :broom:, Long runs :running_woman:

#2067 Clean up warnings in docs
  docs/src/api.md
  docs/src/parameters.md
  src/initial_conditions/initial_conditions.jl
Labels: documentation, House cleaning :broom:

#2074 Use SciMLBase over OrdinaryDiffEq where possible
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/driver.jl
  perf/Manifest.toml
  perf/Project.toml
  perf/benchmark.jl
  perf/flame.jl
  perf/jet.jl
  perf/jet_report_nfailures.jl
  perf/jet_test_nfailures.jl
  src/callbacks/callback_helpers.jl
  src/callbacks/callbacks.jl
  src/initial_conditions/InitialConditions.jl
  src/initial_conditions/initial_conditions.jl
  src/solver/solve.jl
  src/solver/type_getters.jl
  src/utils/utilities.jl
  test/Project.toml
Labels: Dependencies :spider_web:

#2078 Treat idealized_{insolation,clouds} as idealized_h20
  src/cache/cache.jl
  src/parameterized_tendencies/radiation/RRTMGPInterface.jl
  src/parameterized_tendencies/radiation/radiation.jl
  src/solver/model_getters.jl
Labels: House cleaning :broom:, Consistency :dart:

#2088 Remove explicit reference to ClimaAtmos in imports
  src/cache/cache.jl
  src/cache/temporary_quantities.jl
  src/callbacks/callbacks.jl
  src/prognostic_equations/dss.jl
  src/prognostic_equations/limited_tendencies.jl
  src/utils/discrete_hydrostatic_balance.jl
Labels: House cleaning :broom:

#2123 compute prandtl_nvec in prognostic edmfx, add mixing length to plots
  post_processing/contours_and_profiles.jl
  src/cache/edmf_precomputed_quantities.jl
Labels: EDMF :tornado:

#2127 add a function to get draft area
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/edmf_precomputed_quantities.jl
  src/cache/precomputed_quantities.jl
  src/prognostic_equations/edmfx_closures.jl
Labels: EDMF :tornado:

#2130 Remove spaces from cache
  src/cache/cache.jl
Labels: House cleaning :broom:, Latency

#2131 Remove unused fieldvector
  src/cache/cache.jl
  src/callbacks/callbacks.jl
  src/parameterized_tendencies/microphysics/precipitation.jl
Labels: House cleaning :broom:

#2139 Update readme for Julia 1.9.3
  README.md
Labels: documentation, House cleaning :broom:

#2141 Update dependencies
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  perf/flame.jl
  regression_tests/ref_counter.jl
Labels: Dependencies :spider_web:

#2172 Update compats and dependencies
  .dev/Manifest.toml
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  test/Project.toml
Labels: Dependencies :spider_web:

#2170 separate edmfx sgs mass and diffusive fluxes
  config/default_configs/default_edmf_config.yml
  config/longrun_configs/longrun_aquaplanet_amip.yml
  config/model_configs/diagnostic_edmfx_aquaplanet_tke.yml
  config/model_configs/diagnostic_edmfx_bomex_box.yml
  config/model_configs/diagnostic_edmfx_bomex_stretched_box.yml
  config/model_configs/diagnostic_edmfx_dycoms_rf01_box.yml
  config/model_configs/diagnostic_edmfx_gabls_box.yml
  config/model_configs/diagnostic_edmfx_rico_box.yml
  config/model_configs/diagnostic_edmfx_trmm_box.yml
  config/model_configs/diagnostic_edmfx_trmm_stretched_box.yml
  config/model_configs/edmfx_bomex_box.yml
  config/model_configs/edmfx_dycoms_rf01_box.yml
  config/model_configs/edmfx_gabls_box.yml
  config/model_configs/edmfx_rico_box.yml
  config/model_configs/edmfx_trmm_box.yml
  config/model_configs/sphere_baroclinic_wave_rhoe_equilmoist_edmfx.yml
  src/prognostic_equations/edmfx_sgs_flux.jl
  src/prognostic_equations/remaining_tendency.jl
  src/solver/type_getters.jl
  src/solver/types.jl
Labels: EDMF :tornado:
