Repository CliMA/ClimaAtmos.jl, pull requests merged in 2023-06, with the labels that each got.

#1719 Add EDMFX subgrid-scale mass flux
  .buildkite/pipeline.yml
  src/ClimaAtmos.jl
  src/prognostic_equations/edmfx_sgs_flux.jl
  src/prognostic_equations/remaining_tendency.jl
  src/solver/cli_options.jl
  src/solver/type_getters.jl
  src/solver/types.jl
Labels: EDMF :tornado:

#1723 EDMFX bomex box test in the CI (replacing sphere test)
  .buildkite/pipeline.yml
  src/solver/cli_options.jl
Labels: Continuous integration :gear:, EDMF :tornado:

#1683 EDMFX pressure drag
  .buildkite/pipeline.yml
  src/cache/cache.jl
  src/prognostic_equations/edmfx_closures.jl
  src/prognostic_equations/remaining_tendency.jl
  src/solver/cli_options.jl
  src/solver/type_getters.jl
  src/solver/types.jl
Labels: EDMF :tornado:, Launch Buildkite

#1735 Add report jet nfailures script
  .buildkite/pipeline.yml
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/driver.jl
  perf/jet_report_nfailures.jl
  perf/jet_test_nfailures.jl
Labels: Performance monitoring :rocket: :mag:

#1738 Add target job helper
  perf/jet.jl
  src/solver/types.jl
Labels: Performance monitoring :rocket: :mag:, Workflow :gear: :ocean:

#1732 add boundary condition for edmfx
  src/ClimaAtmos.jl
  src/cache/precomputed_quantities.jl
  src/prognostic_equations/edmfx_boundary_condition.jl
Labels: EDMF :tornado:

#1737 Update dependencies
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  perf/flame.jl
  regression_tests/ref_counter.jl
Labels: Dependencies :spider_web:

#1726 add diagnostic edmfx environment variables
  .buildkite/pipeline.yml
  src/cache/precomputed_quantities.jl
  src/prognostic_equations/edmfx_closures.jl
  src/solver/model_getters.jl
  src/solver/types.jl
Labels: EDMF :tornado:

#1715 Update mesh-warp and add earth orography jobs to buildkite longrun pipelines.
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  src/solver/cli_options.jl
  src/solver/type_getters.jl
  src/topography/topography.jl
  src/utils/common_spaces.jl
Labels: enhancement, Long runs :running_woman:

#1739 Skip inference on `fill_with_nans!` unless testing consistency
  src/cache/cache.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/prognostic_equations/implicit/wfact.jl
  src/prognostic_equations/remaining_tendency.jl
  src/solver/types.jl
Labels: Performance monitoring :rocket: :mag:

#1754 Update manifest files
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  perf/flame.jl
Labels: Dependencies :spider_web:

#1762 Log device type being used
  src/solver/type_getters.jl
Labels: Logging :ledger:

#1757 Use report_opt in nfailures
  examples/hybrid/driver.jl
  perf/jet_report_nfailures.jl
  perf/jet_test_nfailures.jl
Labels: Performance monitoring :rocket: :mag:

#1764 Move some code loading to after solve
  examples/hybrid/driver.jl
Labels: Workflow :gear: :ocean:, Latency

#1767 Remove allocs monitoring, fix docs, fix parameter tests
  .buildkite/longruns/pipeline.yml
  perf/allocs.jl
  perf/allocs_per_case.jl
  src/solver/cli_options.jl
  test/parameter_tests.jl
  test/runtests.jl
Labels: documentation, Performance monitoring :rocket: :mag:, bugfix :bug: :hammer:

#1658 Update vector hyperdiffusion to act on full vectors
  docs/src/edmf_equations.md
  docs/src/equations.md
  perf/flame.jl
  regression_tests/ref_counter.jl
  src/cache/temporary_quantities.jl
  src/prognostic_equations/hyperdiffusion.jl
  src/surface_conditions/surface_conditions.jl
Labels: enhancement, Dycore equations

#1763 Upgrade cuda
  .buildkite/JuliaProject.toml
  .buildkite/pipeline.yml
Labels: Dependencies :spider_web:, GPU

#1765 Remove some bycolumn calls
  perf/flame.jl
  src/cache/precomputed_quantities.jl
  src/prognostic_equations/advection.jl
Labels: GPU

#1789 Fix 1788
  src/solver/types.jl
Labels: Coupler compatibility

#1794 Update manifest files
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  perf/flame.jl
Labels: Dependencies :spider_web:

#1793 Log simulated years per day
  src/solver/solve.jl
Labels: Logging :ledger:

#1796 Lower inference failure limit
  perf/jet_test_nfailures.jl
Labels: Inference :mag:

#1690 Port DC problem to ClimaAtmos
  .buildkite/pipeline.yml
  src/initial_conditions/initial_conditions.jl
  src/solver/cli_options.jl
  src/solver/type_getters.jl
Labels: Launch Buildkite

#1787 Add documentation for diagnostic edmfx
  docs/make.jl
  docs/src/diagnostic_edmf_equations.md
Labels: documentation

#1798 Update gpu performance benchmark script
  .buildkite/pipeline.yml
  perf/benchmark_step.jl
  src/solver/solve.jl
Labels: Performance monitoring :rocket: :mag:

#1799 Move fill with nans dispatch
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/prognostic_equations/implicit/wfact.jl
  src/prognostic_equations/remaining_tendency.jl
  src/utils/debug_utils.jl
Labels: Inference :mag:

#1781 Improve GPU test label, use baro wave init
  .buildkite/pipeline.yml
  perf/benchmark_step.jl
Labels: GPU

#1808 Modify dt for failing long-run builds.
  .buildkite/longruns/pipeline.yml
Labels: Long runs :running_woman:

#1811 Update manifest files
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#1815 Fix benchmark params, log resolution
  perf/benchmark_step.jl
  src/solver/type_getters.jl
Labels: Logging :ledger:

#1807 add subgrid scale mass flux for diagnostic edmf
  .buildkite/pipeline.yml
  src/prognostic_equations/edmfx_sgs_flux.jl
Labels: EDMF :tornado:

#1729 EDMFX vertical transport as explicit, hardcode area at first level
  .buildkite/pipeline.yml
  post_processing/contours_and_profiles.jl
  src/cache/precomputed_quantities.jl
  src/callbacks/callbacks.jl
  src/parameters/Parameters.jl
  src/parameters/create_parameters.jl
  src/prognostic_equations/advection.jl
  src/prognostic_equations/edmfx_closures.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/solver/cli_options.jl
Labels: EDMF :tornado:

#1818 Update ClimaComms, RRTMGP, and ClimaCore
  .buildkite/comparison/pipeline.sh
  .buildkite/pipeline.yml
  .buildkite/scaling/pipeline.sh
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  perf/benchmark_step.jl
  perf/flame.jl
  perf/jet_test_nfailures.jl
  post_processing/contours_and_profiles.jl
  post_processing/define_tc_quicklook_profiles.jl
  post_processing/remap/remap_helpers.jl
  regression_tests/ref_counter.jl
  src/parameterized_tendencies/radiation/RRTMGPInterface.jl
  src/parameterized_tendencies/radiation/radiation.jl
  src/solver/cli_options.jl
  src/solver/type_getters.jl
  src/solver/types.jl
  src/utils/debug_utils.jl
  test/Project.toml
Labels: Dependencies :spider_web:

#1817 Update landing readme
  README.md
Labels: documentation

#1820 Add cpu reference
  .buildkite/pipeline.yml
Labels: GPU

#1821 Update manifest files
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  perf/flame.jl
Labels: Dependencies :spider_web:

#1770 Clean up plots and add init conditions to API docs.
  docs/bibliography.bib
  docs/src/api.md
  post_processing/plot/plot_helpers.jl
  post_processing/plot/plot_pipeline.jl
  src/initial_conditions/initial_conditions.jl
Labels: documentation, Continuous integration :gear:, Visualization :art:, Quality assurance

#1824 Move device log to after Logging is configured
  src/solver/type_getters.jl
Labels: Logging :ledger:

#1828 Fix names, return nothing, add dt_save_to_disk to cb flame
  .buildkite/pipeline.yml
  perf/flame.jl
  src/callbacks/callbacks.jl
  src/solver/type_getters.jl
Labels: Performance monitoring :rocket: :mag:

#1831 Improve names, fix configs, add CPU reference benchmark
  .buildkite/pipeline.yml
  perf/benchmark_step.jl
  perf/jet.jl
  src/solver/types.jl
Labels: Performance monitoring :rocket: :mag:

#1829 Break up `save_to_disk_func`
  src/callbacks/callbacks.jl
Labels: Inference :mag:, Allocations

#1835 Do cuda benchmark more carefully
  perf/benchmark_step.jl
Labels: Performance monitoring :rocket: :mag:

#1839 Remove unused argument
  src/parameterized_tendencies/gravity_wave_drag/non_orographic_gravity_wave.jl
  src/parameterized_tendencies/gravity_wave_drag/orographic_gravity_wave.jl
  test/orographic_gravity_wave/ogwd_3d.jl
Labels: Refactor

#1838 Add nsys profiles to gpu perf jobs
  .buildkite/pipeline.yml
Labels: Performance monitoring :rocket: :mag:

#1848 Remove nothings from callback set
  src/solver/type_getters.jl
Labels: Refactor

#1849 Log dt_save_to_sol
  src/solver/type_getters.jl
Labels: Logging :ledger:
