Repository CliMA/ClimaAtmos.jl, pull requests merged in 2023-02, with the labels that each got.

#1306 Delete entrainment_massflux_div_factor
  src/TurbulenceConvection/closures/entr_detr.jl
  src/TurbulenceConvection/types.jl
  tc_driver/generate_namelist.jl
Labels: ClimaParameters :control_knobs:, EDMF :tornado:

#1307 delete retrying for MPI restart test
  .buildkite/pipeline.yml
Labels: Continuous integration :gear:

#1320 Upgrade to ClimaTimeStepeprs v0.7.1
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/types.jl
  ode_compat_examples/Manifest.toml
  ode_compat_examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  test/Project.toml
Labels: Continuous integration :gear:, Time stepping :hourglass:

#1323 Update to Julia 1.8.5
  .buildkite/comparison/pipeline.sh
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/scaling/pipeline.sh
  .dev/Manifest.toml
  README.md
  bors.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/README.md
  ode_compat_examples/Manifest.toml
  perf/Manifest.toml
  post_processing/remap/remap_pipeline.jl
Labels: Dependencies :spider_web:

#1337 Decrease dt for N and S SCM EDMF CI cases, delete anelastic N CI case.
  .buildkite/pipeline.yml
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
Labels: EDMF :tornado:

#1335 Update manifest files
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  ode_compat_examples/Manifest.toml
  perf/Manifest.toml
  regression_tests/ref_counter.jl
Labels: Dependencies :spider_web:

#1286 use weighted interpolation for all divergence reconstructions
  docs/src/equations.md
  examples/hybrid/staggered_nonhydrostatic_model.jl
  regression_tests/ref_counter.jl
  src/tendencies/advection.jl
  src/tendencies/implicit/implicit_tendency.jl
  src/tendencies/implicit/wfact.jl
Labels: Dycore equations

#1330 Remove surface_reference_thermo_state
  examples/hybrid/TurbulenceConvectionUtils.jl
  regression_tests/ref_counter.jl
  tc_driver/Cases.jl
Labels: EDMF :tornado:

#1342 Improve `debug_state`
  src/utilities.jl
Labels: Debugging :mag::bug:

#916 Add edmf sphere example
  .buildkite/pipeline.yml
  examples/hybrid/TurbulenceConvectionUtils.jl
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  src/tendencies/vertical_diffusion_boundary_layer.jl
  tc_driver/Cases.jl
Labels: AMIP Key result, EDMF :tornado:

#1346 Skip post processing + regression tests for sphere edmf job to fix CI
  .buildkite/pipeline.yml
  regression_tests/mse_tables.jl
Labels: Continuous integration :gear:

#1350 Add job for testing n-inference failures
  .buildkite/pipeline.yml
  perf/jet_nfailures.jl
Labels: Performance monitoring :rocket: :mag:

#1309 Add dry edmf imex cases to ci
  .buildkite/pipeline.yml
Labels: EDMF :tornado:

#1202 Add topography hooks and buildkite test cases.
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  artifacts/artifact_funcs.jl
  artifacts/download_artifacts.jl
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  examples/common_spaces.jl
  examples/hybrid/driver.jl
  examples/hybrid/topography_helper.jl
  examples/hybrid/types.jl
  ode_compat_examples/Manifest.toml
  ode_compat_examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  src/ClimaAtmos.jl
  src/tendencies/forcing/held_suarez.jl
  src/tendencies/implicit/wfact.jl
  test/Project.toml
Labels: Consistency :dart:

#1339 entrainment_detrainment cleanup
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/TurbulenceConvection/closures/entr_detr.jl
  src/TurbulenceConvection/closures/nondimensional_exchange_functions.jl
Labels: EDMF :tornado:

#1352 Reorganize perf jobs
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  perf/benchmark.jl
  perf/config_parsed_args.jl
  perf/flame.jl
  perf/inference_flame_init.jl
  perf/jet.jl
  perf/jet_nfailures.jl
  perf/tabulate_perf_summary.jl
  src/model_getters.jl
Labels: Performance monitoring :rocket: :mag:

#1355 Use ntuple in TC kernel
  perf/flame.jl
  src/TurbulenceConvection/closures/entr_detr.jl
  src/TurbulenceConvection/closures/perturbation_pressure.jl
Labels: Refactor, GPU

#1356 Fix environment area initialization
  regression_tests/ref_counter.jl
  tc_driver/initial_conditions.jl
Labels: EDMF :tornado:

#1359 Add mem request to job
  .buildkite/pipeline.yml
Labels: Continuous integration :gear:

#1363 Remove unused properties in TC grid
  examples/hybrid/TurbulenceConvectionUtils.jl
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/Grid.jl
  src/TurbulenceConvection/update_aux.jl
Labels: Refactor

#1362 get rid of get_inversion
  regression_tests/ref_counter.jl
  src/TurbulenceConvection/turbulence_functions.jl
  tc_driver/Cases.jl
  tc_driver/Surface.jl
Labels: EDMF :tornado:

#1344 Generalize quickprofiles script
  post_processing/define_tc_quicklook_profiles.jl
Labels: EDMF :tornado:

#1287 Update horizontal momentum (explicit) tendency term
  .buildkite/longruns/pipeline.yml
  docs/src/equations.md
  regression_tests/ref_counter.jl
  src/tendencies/advection.jl
  src/tendencies/implicit/implicit_tendency.jl
Labels: Dycore equations

#1366 Remove dependence on getindex
  src/TurbulenceConvection/closures/entr_detr.jl
Labels: Refactor

#1329 Aj/filter flags
  examples/hybrid/callbacks.jl
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/variables.jl
Labels: EDMF :tornado:

#1374 Ensure that affect_filter! uses current state values
  examples/hybrid/callbacks.jl
  regression_tests/ref_counter.jl
  src/TurbulenceConvection/EDMF_functions.jl
Labels: EDMF :tornado:

#1373 Add experimental detrainment based on Pi groups
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  regression_tests/mse_tables.jl
  src/TurbulenceConvection/closures/entr_detr.jl
  src/TurbulenceConvection/types.jl
  src/TurbulenceConvection/update_aux.jl
Labels: EDMF :tornado:

#1379 Add NGWD to documentation page
  docs/Manifest.toml
  docs/Project.toml
  docs/bibliography.bib
  docs/make.jl
  docs/src/gravity_wave.md
  docs/src/references.md
Labels: documentation

#1384 Rico initial condition
  regression_tests/ref_counter.jl
  tc_driver/Cases.jl
Labels: EDMF :tornado:

#1377 Replace namelist usage, expand TCParams struct
  examples/hybrid/TurbulenceConvectionUtils.jl
  examples/hybrid/driver.jl
  examples/hybrid/parameter_set.jl
  examples/hybrid/types.jl
  parameters/create_parameters.jl
  perf/flame.jl
  src/TurbulenceConvection/Parameters.jl
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/TurbulenceConvection/types.jl
  src/model_getters.jl
  tc_driver/generate_namelist.jl
  test/test_parameters.jl
Labels: ClimaParameters :control_knobs:, EDMF :tornado:

#1392 Replace q_rai and q_sno with ρq_rai and ρq_sno
  regression_tests/ref_counter.jl
  src/InitialConditions/InitialConditions.jl
  src/TurbulenceConvection/EDMF_Environment.jl
  src/TurbulenceConvection/EDMF_Precipitation.jl
  src/TurbulenceConvection/EDMF_Updrafts.jl
  src/tendencies/precipitation.jl
Labels: EDMF :tornado:

#1364 Reconstructed velocities for momentum advection terms.
  docs/src/equations.md
  examples/hybrid/staggered_nonhydrostatic_model.jl
  regression_tests/ref_counter.jl
  src/precomputed_quantities.jl
  src/tendencies/advection.jl
  src/utilities.jl
Labels: Dycore equations

#1394 Delete unused precipitation fraction model
  examples/hybrid/TurbulenceConvectionUtils.jl
  parameters/create_parameters.jl
  regression_tests/mse_tables.jl
  src/TurbulenceConvection/EDMF_Environment.jl
  src/TurbulenceConvection/EDMF_Precipitation.jl
  src/TurbulenceConvection/EDMF_Updrafts.jl
  src/TurbulenceConvection/Parameters.jl
  src/TurbulenceConvection/microphysics_coupling.jl
  src/TurbulenceConvection/types.jl
  src/model_getters.jl
Labels: EDMF :tornado:

#1391 Call update_aux at the end of init_tc!
  .buildkite/pipeline.yml
  examples/hybrid/TurbulenceConvectionUtils.jl
  post_processing/remap/remap_helpers.jl
  regression_tests/mse_tables.jl
  src/InitialConditions/InitialConditions.jl
  src/TurbulenceConvection/EDMF_Environment.jl
  src/TurbulenceConvection/EDMF_Precipitation.jl
  src/TurbulenceConvection/EDMF_Updrafts.jl
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/microphysics_coupling.jl
  src/TurbulenceConvection/variables.jl
  src/model_getters.jl
  src/tendencies/precipitation.jl
  tc_driver/dycore.jl
Labels: EDMF :tornado:

#1395 add base flux test for the orographic gravity wave
  .buildkite/pipeline.yml
  examples/hybrid/orographic_gravity_wave_helper.jl
  test/orographic_gravity_wave/ogwd_baseflux.jl
Labels: Tests

#1376 Simplify init_tc! to facilitate debugging
  examples/hybrid/TurbulenceConvectionUtils.jl
  regression_tests/mse_tables.jl
  tc_driver/Cases.jl
  tc_driver/dycore.jl
  tc_driver/initial_conditions.jl
Labels: EDMF :tornado:
