Repository CliMA/ClimaAtmos.jl, pull requests merged in 2023-04, with the labels that each got.

#1525 Remove some unused face iterator functions
  src/TurbulenceConvection/Grid.jl
Labels: Refactor, House cleaning :broom:

#1521 Fix bugs in surface velocity computation and explicit algo construction
  perf/flame.jl
  src/precomputed_quantities.jl
  src/staggered_nonhydrostatic_model.jl
  src/utils/type_getters.jl
  src/utils/types.jl
Labels: EDMF :tornado:

#1526 Fix perf bug in edmf update aux
  src/TurbulenceConvection/update_aux.jl
Labels: bug, Performance

#1522 Remove more real_center_indices loops
  src/TurbulenceConvection/EDMF_Updrafts.jl
Labels: Refactor, GPU

#1524 Remove use of real_center_indices
  src/TurbulenceConvection/EDMF_functions.jl
Labels: Refactor, GPU

#1523 Remove more real_center_indices loops
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/Fields.jl
  src/TurbulenceConvection/Grid.jl
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/TurbulenceConvection/closures/perturbation_pressure.jl
  src/TurbulenceConvection/update_aux.jl
Labels: Refactor, GPU

#1528 Remove use of real_center_indices
  examples/hybrid/TurbulenceConvectionUtils.jl
  src/TurbulenceConvection/EDMF_Environment.jl
  src/TurbulenceConvection/EDMF_Precipitation.jl
  src/TurbulenceConvection/EDMF_Updrafts.jl
  src/TurbulenceConvection/types.jl
  src/TurbulenceConvection/update_aux.jl
  src/TurbulenceConvection/variables.jl
Labels: Refactor, GPU

#1529 Make parsed_args_per_job_id work for multi-line statements
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  docs/src/repl_scripts.jl
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/cli_options.jl
  ode_compat_examples/Manifest.toml
  ode_compat_examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  perf/allocs.jl
  perf/config_parsed_args.jl
  perf/tabulate_perf_summary.jl
  src/ClimaAtmos.jl
  src/utils/yaml_helper.jl
  test/Project.toml
Labels: documentation, Workflow :gear: :ocean:

#1538 Remove use of real_center_indices
  src/TurbulenceConvection/update_aux.jl
Labels: Refactor, GPU

#1539 Remove use of real_center_indices
  src/TurbulenceConvection/update_aux.jl
Labels: Refactor, GPU

#1543 Update dependencies
  docs/Manifest.toml
  examples/Manifest.toml
  ode_compat_examples/Manifest.toml
  parameters/create_parameters.jl
  perf/Manifest.toml
  src/TurbulenceConvection/TurbulenceConvection.jl
Labels: Dependencies :spider_web:

#1546 Fix cli script
  examples/hybrid/driver.jl
  src/utils/model_getters.jl
Labels: Workflow :gear: :ocean:

#1549 Delete unused functions
  src/TurbulenceConvection/Fields.jl
Labels: House cleaning :broom:

#1551 Lower ambiguity limit
  test/aqua.jl
Labels: Tests

#1567 Add compat entries for some deps
  Project.toml
Labels: Dependencies :spider_web:

#1527 Add buffer to test
  perf/flame.jl
Labels: Tests

#1516 Move TurbulenceConvectionUtils to src
  examples/hybrid/driver.jl
  examples/hybrid/get_cache_and_tendency.jl
  examples/hybrid/get_callbacks.jl
  src/ClimaAtmos.jl
  src/dycore_equations/sgs_flux_tendencies.jl
  src/utils/surface.jl
  tc_driver/dycore.jl
  tc_driver/dycore_variables.jl
Labels: Refactor, EDMF :tornado:

#1568 Update deps
  .buildkite/pipeline.yml
  .dev/Manifest.toml
  .dev/up_deps.jl
  docs/Manifest.toml
  examples/Manifest.toml
  ode_compat_examples/Manifest.toml
  ode_compat_examples/Project.toml
  perf/Manifest.toml
  perf/flame.jl
Labels: Dependencies :spider_web:

#1575 Move grid-mean precipitations out of EDMF and into parameterizations
  regression_tests/ref_counter.jl
  src/TurbulenceConvection/EDMF_Precipitation.jl
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/TurbulenceConvection/microphysics_coupling.jl
  src/TurbulenceConvection/types.jl
  src/TurbulenceConvection/variables.jl
  src/dycore_equations/sgs_flux_tendencies.jl
  src/parameterizations/microphysics/precipitation.jl
Labels: EDMF :tornado:

#1578 Update RRTMGP
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  src/parameterizations/radiation/RRTMGPInterface.jl
  test/Project.toml
Labels: Dependencies :spider_web:

#1582 Moving precipitation updates into update_aux and closures
  src/TurbulenceConvection/EDMF_Environment.jl
  src/TurbulenceConvection/EDMF_Updrafts.jl
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/TurbulenceConvection/closures/microphysics.jl
  src/TurbulenceConvection/update_aux.jl
  src/TurbulenceConvection/utility_functions.jl
Labels: EDMF :tornado:

#1583 Refactor compute_nh_pressure
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/Parameters.jl
  src/TurbulenceConvection/closures/perturbation_pressure.jl
  src/TurbulenceConvection/types.jl
  src/TurbulenceConvection/update_aux.jl
Labels: EDMF :tornado:

#1574 use total energy as EDMF prognostic variable
  docs/src/edmf_equations.md
  examples/hybrid/get_callbacks.jl
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  src/InitialConditions/atmos_state.jl
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/TurbulenceConvection.jl
  src/TurbulenceConvection/update_aux.jl
  src/dycore_equations/sgs_flux_tendencies.jl
Labels: EDMF :tornado:

#1585 Fix ρ_q_tot and ρ_θ for surface conditions
  examples/hybrid/get_callbacks.jl
  regression_tests/ref_counter.jl
  src/InitialConditions/initial_conditions.jl
  src/TurbulenceConvection/EDMF_functions.jl
  src/TurbulenceConvection/types.jl
  src/dycore_equations/sgs_flux_tendencies.jl
Labels: EDMF :tornado:

#1591 Cleanup mixing length
  src/TurbulenceConvection/closures/mixing_length.jl
  src/TurbulenceConvection/turbulence_functions.jl
  src/TurbulenceConvection/types.jl
  src/TurbulenceConvection/update_aux.jl
Labels: EDMF :tornado:

#1588 Longruns: add first & third-order upwinding jobs
  .buildkite/longruns/pipeline.yml
Labels: Continuous integration :gear:

#1512 Add advection, hyperdiffusion, and limiters to EDMFX model
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  perf/flame.jl
  regression_tests/ref_counter.jl
  src/ClimaAtmos.jl
  src/InitialConditions/InitialConditions.jl
  src/InitialConditions/atmos_state.jl
  src/InitialConditions/initial_conditions.jl
  src/callbacks/callbacks.jl
  src/precomputed_quantities.jl
  src/staggered_nonhydrostatic_model.jl
  src/tendencies/advection.jl
  src/tendencies/hyperdiffusion.jl
  src/tendencies/implicit/implicit_tendency.jl
  src/utils/type_getters.jl
  src/utils/types.jl
  src/utils/utilities.jl
  src/utils/variable_manipulations.jl
Labels: EDMF :tornado:

#1598 Add volume term to EDMFX
  .buildkite/pipeline.yml
  docs/src/edmf_equations.md
  src/InitialConditions/initial_conditions.jl
  src/tendencies/advection.jl
  src/tendencies/hyperdiffusion.jl
  src/tendencies/implicit/implicit_tendency.jl
  src/utils/type_getters.jl
Labels: EDMF :tornado:

#1603 Add and update compats, update deps
  .dev/Manifest.toml
  docs/Manifest.toml
  docs/Project.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  test/Project.toml
Labels: Dependencies :spider_web:

#1605 Add hyperdiffusion to vertical velocity
  .buildkite/pipeline.yml
  docs/src/edmf_equations.md
  docs/src/equations.md
  perf/flame.jl
  regression_tests/ref_counter.jl
  src/tendencies/hyperdiffusion.jl
Labels: EDMF :tornado:

#1618 Fix tracer inference
  perf/flame.jl
  src/tendencies/implicit/schur_complement_W.jl
Labels: Performance
