Repository CliMA/ClimaAtmos.jl, pull requests merged in 2023-01, with the labels that each got.

#1231 Add and use NonOrographicGravityWave type
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
  src/model_getters.jl
  src/tendencies/gravity_wave_parameterization.jl
  src/types.jl
Labels: Refactor

#1235 Update deps
  .dev/Manifest.toml
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  ode_compat_examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#1212 Integrate bubble correction
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  examples/common_spaces.jl
  examples/hybrid/cli_options.jl
  examples/hybrid/driver.jl
  examples/hybrid/types.jl
Labels: enhancement

#1247 Cleanup CI command line arguments for single column edmf tests.
  .buildkite/pipeline.yml
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
Labels: Continuous integration :gear:, ClimaParameters :control_knobs:

#1266 Add theta and velocity to CI profile plots
  post_processing/define_tc_quicklook_profiles.jl
Labels: Continuous integration :gear:, EDMF :tornado:

#1252 Constant entrainment option for refactoring
  .buildkite/pipeline.yml
  examples/hybrid/cli_options.jl
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  src/TurbulenceConvection/closures/entr_detr.jl
  src/TurbulenceConvection/types.jl
Labels: Debugging :mag::bug:, EDMF :tornado:

#1258 Switch the remaining EDMF SCM cases from anelastic to compressible
  .buildkite/pipeline.yml
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
Labels: Continuous integration :gear:, EDMF :tornado:

#1303 Delete unused parameters
  src/TurbulenceConvection/types.jl
  tc_driver/generate_namelist.jl
Labels: ClimaParameters :control_knobs:, EDMF :tornado:

#1290 Un-weighted interpolation: revert to last working long-run.
  .buildkite/pipeline.yml
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  src/tendencies/advection.jl
  src/tendencies/implicit/implicit_tendency.jl
Labels: bugfix :bug: :hammer:, Dycore equations
