Repository CliMA/ClimaAtmos.jl, pull requests merged in 2024-06, with the labels that each got.

#3050 Add precip heating terms
  docs/src/equations.md
  src/cache/temporary_quantities.jl
  src/parameterized_tendencies/microphysics/microphysics_wrappers.jl
  src/parameterized_tendencies/microphysics/precipitation.jl
Labels: Microphysics

#3070 Test 1M EDMF (diag and prog) on GPU
  NEWS.md
  config/model_configs/gpu_diagnostic_edmfx_aquaplanet.yml
  config/model_configs/gpu_prognostic_edmfx_aquaplanet.yml
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/parameterized_tendencies/microphysics/microphysics_wrappers.jl
  src/prognostic_equations/edmfx_entr_detr.jl
Labels: Microphysics

#3074 remove reference state
  NEWS.md
  config/default_configs/default_config.yml
  config/model_configs/plane_agnesi_mountain_test_stretched.yml
  config/model_configs/plane_agnesi_mountain_test_uniform.yml
  config/model_configs/plane_schar_mountain_test_stretched.yml
  config/model_configs/plane_schar_mountain_test_uniform.yml
  config/model_configs/sphere_baroclinic_wave_rhoe_topography_dcmip_rs.yml
  config/model_configs/sphere_held_suarez_rhoe_equilmoist_topography_dcmip.yml
  config/model_configs/sphere_held_suarez_rhoe_topography_dcmip.yml
  config/model_configs/sphere_hydrostatic_balance_rhoe_ft64.yml
  config/model_configs/sphere_ssp_baroclinic_wave_rhoe_equilmoist_dcmip200.yml
  config/model_configs/sphere_ssp_baroclinic_wave_rhoe_equilmoist_earth.yml
  regression_tests/ref_counter.jl
  src/cache/cache.jl
  src/prognostic_equations/advection.jl
  src/prognostic_equations/implicit/implicit_solver.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/solver/type_getters.jl
  src/solver/types.jl
Labels: Breaking :boom:, Numerics

#3079 Update deps
  .dev/Manifest.toml
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  perf/benchmark_step.jl
  src/solver/solve.jl
Labels: Dependencies :spider_web:

#3085 Add CLIMACOMMS_DEVICE=CUDA for gpu job
  .buildkite/pipeline.yml
Labels: bugfix :bug: :hammer:

#3084 Add precipitation surface fluxes for 1M microphysics
  NEWS.md
  Project.toml
  config/model_configs/diagnostic_edmfx_bomex_box.yml
  config/model_configs/diagnostic_edmfx_bomex_stretched_box.yml
  config/model_configs/diagnostic_edmfx_dycoms_rf01_box.yml
  config/model_configs/diagnostic_edmfx_dycoms_rf01_explicit_box.yml
  config/model_configs/diagnostic_edmfx_gabls_box.yml
  config/model_configs/diagnostic_edmfx_rico_box.yml
  config/model_configs/diagnostic_edmfx_test_box.yml
  config/model_configs/diagnostic_edmfx_trmm_box.yml
  config/model_configs/diagnostic_edmfx_trmm_box_0M.yml
  config/model_configs/diagnostic_edmfx_trmm_stretched_box.yml
  config/model_configs/gpu_prognostic_edmfx_aquaplanet.yml
  config/model_configs/prognostic_edmfx_adv_test_column.yml
  config/model_configs/prognostic_edmfx_aquaplanet.yml
  config/model_configs/prognostic_edmfx_bomex_box.yml
  config/model_configs/prognostic_edmfx_bomex_column.yml
  config/model_configs/prognostic_edmfx_bomex_fixtke_column.yml
  config/model_configs/prognostic_edmfx_bomex_implicit_column.yml
  config/model_configs/prognostic_edmfx_bomex_pigroup_column.yml
  config/model_configs/prognostic_edmfx_bomex_stretched_column.yml
  config/model_configs/prognostic_edmfx_dycoms_rf01_column.yml
  config/model_configs/prognostic_edmfx_gabls_column.yml
  config/model_configs/prognostic_edmfx_gcmdriven_column.yml
  config/model_configs/prognostic_edmfx_rico_column.yml
  config/model_configs/prognostic_edmfx_simpleplume_column.yml
  config/model_configs/prognostic_edmfx_trmm_column.yml
  config/model_configs/prognostic_edmfx_trmm_column_0M.yml
  config/model_configs/single_column_precipitation_test.yml
  post_processing/ci_plots.jl
  src/diagnostics/Diagnostics.jl
  src/diagnostics/core_diagnostics.jl
  src/diagnostics/default_diagnostics.jl
  src/parameterized_tendencies/microphysics/precipitation.jl
  src/prognostic_equations/advection.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/prognostic_equations/surface_temp.jl
  test/parameterized_tendencies/microphysics/precipitation.jl
Labels: Microphysics, Breaking :boom:

#3095 Try fixing longruns
  src/parameterized_tendencies/microphysics/precipitation.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
Labels: Microphysics

#3121 Update dependencies
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#3126 Add cloud diagnostics for diagnostic edmf
  config/default_configs/default_config.yml
  config/model_configs/diagnostic_edmfx_bomex_box.yml
  src/cache/cloud_fraction.jl
  src/solver/model_getters.jl
  src/solver/types.jl
Labels: Microphysics

#3150 added rcemipii insolation, changed insolation argument
  NEWS.md
  config/default_configs/default_config.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ss_1process.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ss_2process.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ss_4process.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ws_1process.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ws_2process.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ws_4process.yml
  config/longrun_configs/amip_target_diagedmf.yml
  config/longrun_configs/longrun_aquaplanet_dyamond.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_tvinsol_0M_slabocean.yml
  config/model_configs/aquaplanet_diagedmf.yml
  config/model_configs/aquaplanet_progedmf.yml
  config/model_configs/aquaplanet_rhoe_equil_clearsky_tvinsol_0M_slabocean.yml
  config/model_configs/gpu_aquaplanet_dyamond.yml
  config/model_configs/rcemipii_sphere_diagnostic_edmfx.yml
  config/model_configs/single_column_radiative_equilibrium_allsky_idealized_clouds.yml
  config/model_configs/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_raw_zonallyasymmetric.yml
  config/model_configs/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_res.yml
  config/model_configs/sphere_aquaplanet_rhoe_nonequilmoist_allsky.yml
  config/perf_configs/flame_perf_gw.yml
  src/callbacks/callbacks.jl
  src/parameterized_tendencies/radiation/RRTMGPInterface.jl
  src/parameterized_tendencies/radiation/radiation.jl
  src/solver/model_getters.jl
  src/solver/type_getters.jl
  src/solver/types.jl
Labels: Breaking :boom:
