Repository CliMA/ClimaAtmos.jl, pull requests merged in 2024-07, with the labels that each got.

#3156 add lookup table for aerosols
  src/parameterized_tendencies/radiation/RRTMGPInterface.jl
Labels: enhancement, radiation ☀️

#3172 Update to CloudMicrophysics v0.22
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Microphysics

#3167 rename radiation_model to rrtmgp_model
  NEWS.md
  src/cache/surface_albedo.jl
  src/callbacks/callbacks.jl
  src/diagnostics/radiation_diagnostics.jl
  src/parameterized_tendencies/radiation/radiation.jl
  test/surface_albedo.jl
Labels: Breaking :boom:

#3173 update aerosol in the boundary layer for radiation
  src/parameterized_tendencies/radiation/RRTMGPInterface.jl
Labels: bugfix :bug: :hammer:

#3175 Use ClimaCore dz_field
  src/callbacks/callbacks.jl
  src/parameterized_tendencies/radiation/radiation.jl
Labels: Refactor

#2990 Cleanup old folders on central
  regression_tests/move_output.jl
  regression_tests/self_reference_or_path.jl
Labels: House cleaning :broom:, Workflow :gear: :ocean:

#3180 add different aerosol types to radiation
  NEWS.md
  src/cache/tracer_cache.jl
  src/callbacks/callbacks.jl
  src/parameterized_tendencies/radiation/radiation.jl
Labels: enhancement

#3179 Wip on adding prescribed cloud droplet number concentration
  src/parameterized_tendencies/microphysics/microphysics_wrappers.jl
  src/parameters/create_parameters.jl
  toml/single_column_precipitation_test.toml
Labels: Microphysics

#3190 Update dependencies
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#3218 Fix ClimaCalibrate compat
  calibration/experiments/sphere_held_suarez_rhoe_equilmoist/Project.toml
  calibration/test/Project.toml
  calibration/test/e2e_test.jl
  src/solver/yaml_helper.jl
Labels: bugfix :bug: :hammer:
