Repository CliMA/ClimaAtmos.jl, pull requests merged in 2024-05, with the labels that each got.

#2978 Update ClimaCore compat and dependencies
  .dev/Manifest.toml
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#2991 Print better warnings in regression tests
  regression_tests/compute_mse.jl
Labels: Debugging :mag::bug:

#2070 Remove perf_mode
  config/default_configs/default_config.yml
  config/perf_configs/flame_perf_target_tracers.yml
  perf/flame.jl
  src/initial_conditions/InitialConditions.jl
  src/initial_conditions/atmos_state.jl
  src/solver/model_getters.jl
  src/solver/type_getters.jl
  src/solver/types.jl
Labels: House cleaning :broom:

#3033 Move remaining precipitation tests from driver to tests
  config/default_configs/default_config.yml
  config/model_configs/single_column_precipitation_test.yml
  examples/hybrid/driver.jl
  test/parameterized_tendencies/microphysics/precipitation.jl
Labels: Microphysics

#3039 Upgrade dependencies
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  perf/benchmark.jl
Labels: Dependencies :spider_web:

#3043 Fix CI
  perf/benchmark.jl
Labels: Continuous integration :gear:
