Repository CliMA/ClimaAtmos.jl, pull requests merged in 2024-02, with the labels that each got.

#2603 Update to new RRTMGP interface
  Project.toml
  examples/Manifest.toml
  perf/Manifest.toml
  regression_tests/ref_counter.jl
  src/callbacks/callbacks.jl
  src/parameterized_tendencies/radiation/RRTMGPInterface.jl
  src/parameterized_tendencies/radiation/radiation.jl
Labels: API, Breaking :boom:

#2616 Turn off diagnostics and IO for GPU pipeline
  config/gpu_configs/central_gpu_hs_rhoe_equil_55km_nz63_0M.yml
  config/gpu_configs/gpu_aquaplanet_dyamond.yml
  config/gpu_configs/gpu_diagnostic_edmfx_aquaplanet.yml
  config/gpu_configs/gpu_hs_rhoe_equil_55km_nz63_0M.yml
  config/gpu_configs/gpu_hs_rhoe_equil_55km_nz63_0M_4process.yml
  config/gpu_configs/target_gpu_implicit_baroclinic_wave.yml
  config/gpu_configs/target_gpu_implicit_baroclinic_wave_4process.yml
Labels: Performance monitoring :rocket: :mag:, GPU

#2615 + alloc tests per CTS func call
  perf/benchmark.jl
Labels: Performance monitoring :rocket: :mag:

#2617 Fix precipitation test
  config/model_configs/single_column_precipitation_test.yml
  examples/hybrid/driver.jl
  perf/flame.jl
Labels: Microphysics, Tests

#2625 Report walltime_per_timestep
  src/solver/solve.jl
Labels: Performance monitoring :rocket: :mag:

#2580 Make tracer vert adv always explicit
  src/prognostic_equations/advection.jl
  src/prognostic_equations/implicit/implicit_solver.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
Labels: Microphysics

#2626 Update precipitation tendency to fix boundary condition
  config/default_configs/default_config.yml
  config/model_configs/single_column_precipitation_test.yml
  config/model_configs/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_res.yml
  src/prognostic_equations/implicit/implicit_solver.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/solver/type_getters.jl
  src/solver/types.jl
  src/utils/abbreviations.jl
Labels: Microphysics

#2629 Create nsys report for gpu dyamond simulation
  .buildkite/pipeline.yml
Labels: Performance monitoring :rocket: :mag:

#2636 Add 1-moment microphysics coupled to grid-mean state to longruns
  .buildkite/longruns/pipeline.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_1M.yml
  docs/src/equations.md
  docs/src/longruns.md
  src/cache/precipitation_precomputed_quantities.jl
  src/parameterized_tendencies/microphysics/precipitation.jl
  src/prognostic_equations/hyperdiffusion.jl
  toml/longrun_1M.toml
Labels: Microphysics

#2648 Prep moving diagnostics to callbacks folder
  perf/flame.jl
  src/ClimaAtmos.jl
  src/callbacks/get_callbacks.jl
  src/diagnostics/diagnostic.jl
  src/diagnostics/hdf5_writer.jl
  src/diagnostics/netcdf_writer.jl
  src/solver/type_getters.jl
Labels: Refactor

#2660 Improve stack traces in offline perf scripts
  perf/benchmark.jl
  perf/benchmark_dump.jl
  perf/benchmark_step.jl
  perf/common.jl
Labels: Performance monitoring :rocket: :mag:

#2628 Add support for comparison plots
  perf/flame.jl
  post_processing/ci_plots.jl
Labels: Continuous integration :gear:, Visualization :art:, Diagnostics

#2663 Update dependencies
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  perf/flame.jl
Labels: Dependencies :spider_web:

#2668 Add cloud diagnostics to flame graph
  config/perf_configs/flame_perf_target_callbacks.yml
  perf/flame.jl
Labels: Performance monitoring :rocket: :mag:

#2672 Try to fix lr hydrostatic balance func for gpus
  .buildkite/longruns/pipeline.yml
  src/utils/discrete_hydrostatic_balance.jl
Labels: GPU

#2590 add support for deep atmosphere
  .buildkite/pipeline.yml
  Project.toml
  config/default_configs/default_config.yml
  config/model_configs/deep_sphere_baroclinic_wave_rhoe_equilmoist.yml
  config/model_configs/sphere_held_suarez_rhoe_hightop.yml
  docs/src/equations.md
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  regression_tests/mse_tables.jl
  regression_tests/ref_counter.jl
  src/cache/cache.jl
  src/diagnostics/core_diagnostics.jl
  src/diagnostics/netcdf_writer.jl
  src/prognostic_equations/advection.jl
  src/solver/type_getters.jl
  src/utils/common_spaces.jl
Labels: Dependencies :spider_web:, Dycore equations, GPU

#2673 Hoist and precompute common variables
  perf/flame.jl
  src/cache/cloud_fraction.jl
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/precomputed_quantities.jl
  src/callbacks/callbacks.jl
  src/prognostic_equations/gm_sgs_closures.jl
Labels: Performance

#2680 Shrink EnvBuoyGradVars
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/prognostic_equations/buoyancy_gradients.jl
  src/prognostic_equations/gm_sgs_closures.jl
  src/solver/types.jl
Labels: Performance

#2689 Fuse dss calls
  src/prognostic_equations/hyperdiffusion.jl
Labels: Performance

#2667 Cover entire globe with NetCDF
  src/diagnostics/netcdf_writer.jl
Labels: Visualization :art:, Diagnostics

#2690 Adapt interpolation object for GPU runs.
  .dev/Manifest.toml
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  src/solver/type_getters.jl
Labels: GPU

#2714 Update deps
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:
