Repository CliMA/ClimaAtmos.jl, pull requests merged in 2024-04, with the labels that each got.

#2859 use specific humidity as precipitation threshold
  regression_tests/ref_counter.jl
  src/parameterized_tendencies/microphysics/microphysics_wrappers.jl
Labels: Microphysics

#2864 add an option to turn off tendencies
  .buildkite/longruns/pipeline.yml
  config/default_configs/default_edmf_config.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_progedmf_diffonly_0M.yml
  config/model_configs/prognostic_edmfx_simpleplume_column.yml
  src/ClimaAtmos.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/prognostic_equations/remaining_tendency.jl
  src/prognostic_equations/zero_gridscale_tendency.jl
  src/prognostic_equations/zero_tendency.jl
  src/solver/model_getters.jl
  src/solver/type_getters.jl
  src/solver/types.jl
  toml/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_progedmf_0M.toml
Labels: API

#2869 Add some NVTX annotations
  src/cache/cloud_fraction.jl
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/prognostic_equations/gm_sgs_closures.jl
Labels: Performance monitoring :rocket: :mag:

#2874 Add cloud diagnostics per stage option
  .buildkite/gpu_pipeline/pipeline.yml
  .buildkite/pipeline.yml
  config/default_configs/default_config.yml
  config/gpu_configs/central_cloud_diag_gpu_hs_rhoe_equil_55km_nz63_0M.yml
  src/cache/cloud_fraction.jl
  src/cache/precomputed_quantities.jl
  src/callbacks/get_callbacks.jl
  src/solver/model_getters.jl
  src/solver/type_getters.jl
  src/solver/types.jl
Labels: Performance monitoring :rocket: :mag:

#2871 Cleanup in 0M diagnostic EDMF
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/parameterized_tendencies/microphysics/precipitation.jl
  src/prognostic_equations/edmfx_precipitation.jl
Labels: Microphysics

#2771 Interface tests: ClimaAtmos spaces, callbacks and parameterized tendency construction
  .buildkite/pipeline.yml
  test/callbacks.jl
  test/parameterized_tendencies/gravity_wave/gw_plotutils.jl
  test/parameterized_tendencies/gravity_wave/non_orographic_gravity_wave/nogw_test_3d.jl
  test/parameterized_tendencies/gravity_wave/non_orographic_gravity_wave/nogw_test_mima.jl
  test/parameterized_tendencies/gravity_wave/non_orographic_gravity_wave/nogw_test_single_column.jl
  test/parameterized_tendencies/gravity_wave/orographic_gravity_wave/ogwd_3d.jl
  test/parameterized_tendencies/gravity_wave/orographic_gravity_wave/ogwd_baseflux.jl
  test/parameterized_tendencies/microphysics/precipitation.jl
  test/parameterized_tendencies/sponge/rayleigh_sponge.jl
  test/parameterized_tendencies/sponge/viscous_sponge.jl
  test/parameters/parameter_tests.jl
  test/rrtmgp_interface.jl
  test/runtests.jl
  test/solver/model_getters.jl
  test/test_helpers.jl
  test/topography.jl
  test/utilities.jl
Labels: Tests, Quality assurance

#2897 Non-equilibrium cloud formation
  .buildkite/pipeline.yml
  config/model_configs/sphere_aquaplanet_rhoe_nonequilmoist_allsky_gw_res.yml
  post_processing/ci_plots.jl
  src/ClimaAtmos.jl
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/precipitation_precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/parameterized_tendencies/microphysics/cloud_condensate.jl
  src/parameterized_tendencies/microphysics/microphysics_wrappers.jl
  src/parameterized_tendencies/microphysics/precipitation.jl
  src/parameters/Parameters.jl
  src/parameters/create_parameters.jl
  src/prognostic_equations/remaining_tendency.jl
  test/parameterized_tendencies/microphysics/precipitation.jl
Labels: enhancement, Microphysics

#2899 Print benchmark results before tests
  perf/benchmark.jl
Labels: Performance monitoring :rocket: :mag:

#2915 Update dependencies
  .dev/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#2926 Hoist BidiagonalMatrixRow expressions for prog edmf
  .buildkite/pipeline.yml
  src/cache/precomputed_quantities.jl
  src/prognostic_equations/implicit/implicit_solver.jl
Labels: GPU

#2962 Output CF, q_liq and q_ice from quadratures and use it in radiation
  examples/hybrid/driver.jl
  src/cache/cloud_fraction.jl
  src/cache/precomputed_quantities.jl
  src/callbacks/callbacks.jl
  src/diagnostics/core_diagnostics.jl
Labels: Microphysics
