Repository CliMA/ClimaAtmos.jl, pull requests merged in 2024-01, with the labels that each got.

#2472 add a filter to sgs mass flux for diagnostic edmf
  src/prognostic_equations/edmfx_sgs_flux.jl
Labels: EDMF :tornado:

#2483 Only merge PDFs that really exist
  post_processing/ci_plots.jl
Labels: bugfix :bug: :hammer:

#2501 Update long-run builds and add summary of scheduled diagnostics.
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_tvinsol_0M_slabocean.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_gray_0M.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_clearsky_tvinsol_0M_slabocean.yml
  src/solver/type_getters.jl
Labels: Long runs :running_woman:

#2427 Add missing blocks to the dycore Jacobian
  .buildkite/pipeline.yml
  perf/flame.jl
  regression_tests/ref_counter.jl
  src/cache/cache.jl
  src/cache/temporary_quantities.jl
  src/parameters/Parameters.jl
  src/prognostic_equations/implicit/implicit_solver.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/solver/type_getters.jl
  src/utils/abbreviations.jl
  src/utils/utilities.jl
Labels: enhancement

#2520 Add gaussian smoothing
  .dev/Manifest.toml
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  perf/Project.toml
  src/solver/type_getters.jl
  src/utils/utilities.jl
  test/Project.toml
  test/orographic_gravity_wave/ogwd_3d.jl
  test/utilities.jl
Labels: Dependencies :spider_web:, House cleaning :broom:, Latency

#2524 add option for 0 or 1 cloud fraction
  config/default_configs/default_config.yml
  config/longrun_configs/longrun_aquaplanet_dyamond.yml
  config/model_configs/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_raw_zonallyasymmetric.yml
  src/cache/cloud_fraction.jl
  src/callbacks/callbacks.jl
  src/solver/model_getters.jl
  src/solver/type_getters.jl
  src/solver/types.jl
Labels: enhancement

#2537 tag v0.19.1
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#2367 Improve `buoyancy_gradients` design
  src/ClimaAtmos.jl
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/prognostic_equations/buoyancy_gradients.jl
  src/prognostic_equations/gm_sgs_closures.jl
  src/solver/types.jl
Labels: Refactor

#2543 Add spectra in postprocessing pipeline
  post_processing/ci_plots.jl
  src/diagnostics/netcdf_writer.jl
Labels: Visualization :art:

#2549 Use depth-limited type printing for non-interactive runs
  examples/hybrid/driver.jl
Labels: Logging :ledger:, Stacktrace

#2550 Introduce z_reference in NetCDF for topo runs
  config/model_configs/sphere_baroclinic_wave_rhoe_topography_dcmip_rs.yml
  docs/src/diagnostics.md
  post_processing/ci_plots.jl
  src/diagnostics/netcdf_writer.jl
Labels: enhancement, Diagnostics

#2540 Update upwinding based on FCT
  config/default_configs/default_config.yml
  src/prognostic_equations/advection.jl
  src/prognostic_equations/implicit/implicit_solver.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/solver/type_getters.jl
  src/solver/types.jl
Labels: Numerics

#2559 Add 0M microphysics to prognostic edmf
  perf/flame.jl
  src/ClimaAtmos.jl
  src/cache/precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/parameterized_tendencies/microphysics/precipitation.jl
  src/prognostic_equations/edmfx_precipitation.jl
  src/prognostic_equations/remaining_tendency.jl
Labels: Microphysics, EDMF :tornado:

#2572 Truncate stack traces in tests
  test/runtests.jl
Labels: Tests, Logging :ledger:

#2584 Lower JET failure limit
  perf/jet_test_nfailures.jl
Labels: Performance tests

#2583 Add a flame graph for one of our gpu jobs
  .buildkite/pipeline.yml
  config/perf_configs/flame_gpu_implicit_barowave_moist.yml
  perf/flame.jl
  perf/invalidations.jl
  perf/jet.jl
  perf/jet_report_nfailures.jl
  perf/jet_test_nfailures.jl
Labels: Performance monitoring :rocket: :mag:

#2592 fixes to rain diff
  src/prognostic_equations/hyperdiffusion.jl
  src/prognostic_equations/vertical_diffusion_boundary_layer.jl
Labels: Microphysics

#2600 Make number of NetCDF points YAML controllable
  config/default_configs/default_config.yml
  config/model_configs/single_column_radiative_equilibrium_gray.yml
  src/solver/type_getters.jl
Labels: Diagnostics

#2581 Update dependencies
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  regression_tests/ref_counter.jl
  test/Project.toml
Labels: Dependencies :spider_web:
