Repository CliMA/ClimaAtmos.jl, pull requests merged in 2024-03, with the labels that each got.

#2734 Update ClimaTimeSteppers
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  regression_tests/ref_counter.jl
Labels: Time stepping :hourglass:

#2732 deep-sphere branch in edmf advection equation
  src/prognostic_equations/advection.jl
Labels: EDMF :tornado:, Dycore equations

#2728 Update test and perf env to use CairoMakie for output
  .buildkite/pipeline.yml
  examples/Manifest.toml
  examples/Project.toml
  examples/hybrid/driver.jl
  perf/Manifest.toml
  perf/Project.toml
  perf/benchmark_dump.jl
  perf/tabulate_perf_summary.jl
  test/Project.toml
  test/gravity_wave/gw_plotutils.jl
  test/gravity_wave/non_orographic_gravity_wave/nogw_test_3d.jl
  test/gravity_wave/non_orographic_gravity_wave/nogw_test_mima.jl
  test/gravity_wave/non_orographic_gravity_wave/nogw_test_single_column.jl
  test/gravity_wave/orographic_gravity_wave/ogwd_3d.jl
  test/gravity_wave/orographic_gravity_wave/ogwd_baseflux.jl
Labels: bikeshedding, Visualization :art:, Tests

#2754 Use new ClimaTimeSteppers with fused T_exp_T_lim
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/hybrid/driver.jl
  perf/Manifest.toml
  perf/benchmark.jl
  perf/jet_report_nfailures.jl
  src/prognostic_equations/remaining_tendency.jl
  src/solver/type_getters.jl
Labels: Performance

#2758 Fuse dynamic and tracer tendency dss calls
  perf/benchmark.jl
  perf/jet_report_nfailures.jl
  perf/tabulate_perf_summary.jl
  src/prognostic_equations/hyperdiffusion.jl
  src/prognostic_equations/limited_tendencies.jl
  src/prognostic_equations/remaining_tendency.jl
Labels: Performance

#2674 Try comparison feature
  examples/hybrid/driver.jl
  post_processing/ci_plots.jl
Labels: Visualization :art:, Workflow :gear: :ocean:

#2736 Update to CMv0.17 (old parameters, no kwargs)
  Project.toml
Labels: Microphysics

#2731 Update longrun pipeline (topography runs)
  .buildkite/longruns/pipeline.yml
  .buildkite/longruns_gpu/pipeline.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_deepatmos.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth.yml
  docs/src/longruns.md
  post_processing/ci_plots.jl
  toml/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth.toml
Labels: Long runs :running_woman:, GPU

#2763 Add default diagnostics and plots for 1M scheme
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_1M.yml
  post_processing/ci_plots.jl
  src/diagnostics/default_diagnostics.jl
  toml/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_1M.toml
Labels: Microphysics, Diagnostics

#2765 Add a GPU 1-moment microphysics job to the CI
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  Project.toml
  config/gpu_configs/gpu_aquaplanet_clearsky_1M.yml
  examples/Manifest.toml
  post_processing/ci_plots.jl
  src/parameterized_tendencies/microphysics/precipitation.jl
  src/parameters/create_parameters.jl
  src/prognostic_equations/implicit/implicit_solver.jl
  toml/gpu_aquaplanet_clearsky_1M.toml
Labels: Microphysics

#2740 Tests for ClimaAtmos utilities
  test/utilities.jl
Labels: Tests, Quality assurance

#2791 Held-suarez deep-atmosphere longrun config
  .buildkite/longruns_gpu/pipeline.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_deepatmos.yml
  config/longrun_configs/longrun_hs_rhoe_equil_55km_nz63_0M_deepatmos.yml
  docs/src/longruns.md
  post_processing/ci_plots.jl
Labels: Long runs :running_woman:

#2741 Add config and update spaces to use SLEVE coords (optional) with topography
  .buildkite/longruns_gpu/pipeline.yml
  config/default_configs/default_config.yml
  config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth_sleve.yml
  src/solver/type_getters.jl
  src/utils/common_spaces.jl
  test/gravity_wave/orographic_gravity_wave/ogwd_3d.jl
  toml/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth_sleve.toml
Labels: Long runs :running_woman:

#2802 Common-spaces (SLEVE) bugfix : Constrain types.
  src/utils/common_spaces.jl
Labels: Long runs :running_woman:, bugfix :bug: :hammer:

#2794 Add a GPU longrun with 1M microphysics (aquaplanet grid mean)
  .buildkite/longruns_gpu/pipeline.yml
  config/longrun_configs/longrun_aquaplanet_clearsky_1M.yml
  docs/src/equations.md
  docs/src/longruns.md
  post_processing/ci_plots.jl
  src/parameterized_tendencies/microphysics/precipitation.jl
  src/prognostic_equations/hyperdiffusion.jl
Labels: Microphysics

#2804 Add nsys profiling back in
  .buildkite/pipeline.yml
Labels: Performance monitoring :rocket: :mag:

#2805 Simplify surface function
  src/surface_conditions/surface_conditions.jl
Labels: Performance

#2808 fix docstring
  config/default_configs/default_config.yml
Labels: Microphysics

#2813 add 1M to GPU scaling and dyamond setup
  .buildkite/pipeline.yml
  config/gpu_configs/gpu_aquaplanet_clearsky_1M.yml
  config/gpu_configs/gpu_aquaplanet_dyamond.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ss_1process.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ss_2process.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ss_4process.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ws_1process.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ws_2process.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ws_4process.yml
  config/longrun_configs/longrun_aquaplanet_clearsky_1M.yml
  post_processing/ci_plots.jl
  toml/gpu_aquaplanet_clearsky_1M.toml
Labels: Microphysics

#2816 Update deps
  examples/Manifest.toml
  perf/Manifest.toml
  perf/flame.jl
Labels: Dependencies :spider_web:

#2814 Fix an inference failure in gpu prognostic edmf
  perf/flame.jl
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/utils/variable_manipulations.jl
Labels: EDMF :tornado:, GPU

#2819 Fix updraft_top computation on the gpu
  .buildkite/pipeline.yml
  src/cache/precomputed_quantities.jl
  src/prognostic_equations/edmfx_closures.jl
Labels: EDMF :tornado:, GPU

#2832 Use unrolled_dot_product to fix inference
  src/cache/diagnostic_edmf_precomputed_quantities.jl
Labels: Performance, GPU

#2833 Update dependencies
  examples/Manifest.toml
  perf/Manifest.toml
  perf/flame.jl
Labels: Dependencies :spider_web:, GPU

#2828 Group NCDatasets.sync calls
  perf/benchmark_netcdf_io.jl
  src/diagnostics/diagnostic.jl
  src/diagnostics/netcdf_writer.jl
  src/solver/type_getters.jl
Labels: Performance monitoring :rocket: :mag:, Performance

#2840 Add nsys profile to gpu_aquaplanet_diagedmf
  .buildkite/gpu_pipeline/pipeline.yml
Labels: Performance monitoring :rocket: :mag:

#2850 Disable default compression of NetCDF files
  perf/benchmark_netcdf_io.jl
  src/diagnostics/netcdf_writer.jl
Labels: Diagnostics

#2842 Update jet script
  perf/jet.jl
Labels: Performance monitoring :rocket: :mag:

#2844 Throw a more informative error for unsupported config dictionary entries
  src/solver/model_getters.jl
  src/solver/yaml_helper.jl
Labels: Launch Buildkite

#2851 add some edmf diagnostics for debugging
  config/model_configs/prognostic_edmfx_bomex_box.yml
  config/model_configs/prognostic_edmfx_bomex_fixtke_box.yml
  config/model_configs/prognostic_edmfx_bomex_stretched_box.yml
  config/model_configs/prognostic_edmfx_dycoms_rf01_box.yml
  config/model_configs/prognostic_edmfx_gabls_box.yml
  config/model_configs/prognostic_edmfx_rico_column.yml
  config/model_configs/prognostic_edmfx_simpleplume_column.yml
  config/model_configs/prognostic_edmfx_trmm_column.yml
  config/model_configs/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_res.yml
  post_processing/ci_plots.jl
  src/diagnostics/Diagnostics.jl
  src/diagnostics/edmfx_diagnostics.jl
Labels: enhancement

#2847 Separate precipitation sources and sinks
  regression_tests/ref_counter.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/parameterized_tendencies/microphysics/microphysics_wrappers.jl
  src/parameterized_tendencies/microphysics/precipitation.jl
  src/prognostic_equations/remaining_tendency.jl
Labels: Microphysics
