Repository CliMA/ClimaAtmos.jl, pull requests merged in 2024-10, with the labels that each got.

#3347 Update ClimaDiagnostics
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  perf/flame.jl
Labels: Dependencies :spider_web:

#3346 Use ClimaReproducibilityTests.jl
  examples/Manifest.toml
  examples/Project.toml
  reproducibility_tests/compute_mse.jl
  reproducibility_tests/reproducibility_tests.jl
  reproducibility_tests/test_mse.jl
  test/Project.toml
Labels: Dependencies :spider_web:, Reproducibility 🎲

#3349 Decrease JET failure limit
  perf/jet_test_nfailures.jl
Labels: Inference :mag:

#3329 Protect reproducibility tests against manual merge
  reproducibility_tests/move_output.jl
Labels: Workflow :gear: :ocean:

#3332 up SurfaceFluxes in examples
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  reproducibility_tests/ref_counter.jl
Labels: Dycore equations

#3358 Remove nsys report from gpu_aquaplanet_dyamond
  .buildkite/pipeline.yml
Labels: Continuous integration :gear:

#3357 Update dependencies
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#3363 Tag v0.27.6
  NEWS.md
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Continuous integration :gear:
