Repository CliMA/ClimaAtmos.jl, pull requests merged in 2025-05, with the labels that each got.

#3789 adding noneq implicit flag
  config/default_configs/default_config.yml
  config/model_configs/amip_target_edonly_nonequil.yml
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/prognostic_equations/remaining_tendency.jl
  src/solver/type_getters.jl
  src/solver/types.jl
Labels: Microphysics

#3792 Make nogw_callback no-op when there's no GW
  src/callbacks/callbacks.jl
  src/parameterized_tendencies/gravity_wave_drag/non_orographic_gravity_wave.jl
Labels: bugfix :bug: :hammer:, gravity wave

#3798 Inline functions that return broadcasted objects
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/initial_conditions/initial_conditions.jl
  src/prognostic_equations/edmfx_sgs_flux.jl
  src/prognostic_equations/gm_sgs_closures.jl
  src/prognostic_equations/vertical_diffusion_boundary_layer.jl
  src/utils/utilities.jl
  test/utilities.jl
Labels: Refactor

#3794 Update turbulent Prandtl number
  .buildkite/Manifest-v1.11.toml
  Project.toml
  reproducibility_tests/ref_counter.jl
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/parameters/Parameters.jl
  src/parameters/create_parameters.jl
  src/prognostic_equations/edmfx_closures.jl
  src/prognostic_equations/gm_sgs_closures.jl
Labels: EDMF :tornado:

#3818 Fix viscous sponge
  reproducibility_tests/ref_counter.jl
  src/prognostic_equations/remaining_tendency.jl
Labels: bugfix :bug: :hammer:

#3813 Move limiter for rhs out of wrappers
  reproducibility_tests/ref_counter.jl
  src/parameterized_tendencies/microphysics/microphysics_wrappers.jl
  src/prognostic_equations/limited_tendencies.jl
Labels: Microphysics

#3831 Update dependencies
  .buildkite/Manifest-v1.11.toml
Labels: dependencies

#3799 Use space instead of field, improve docs
  src/cache/precomputed_quantities.jl
  src/utils/utilities.jl
  test/utilities.jl
Labels: documentation, Refactor
