Repository CliMA/ClimaAtmos.jl, pull requests merged in 2025-03, with the labels that each got.

#3665 Move vertical passive tracer advection to explicit tendency
  reproducibility_tests/ref_counter.jl
  src/prognostic_equations/advection.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
Labels: Microphysics

#3660 Prescribe N in r_eff liquid clouds
  Project.toml
  reproducibility_tests/ref_counter.jl
  src/callbacks/callbacks.jl
  src/parameters/create_parameters.jl
Labels: Microphysics

#3686 Lower jet `n_allowed_failures`
  perf/jet_test_nfailures.jl
Labels: Tests, Latency

#3691 Remove data_loader in RRTMGPInterface
  src/ClimaAtmos.jl
  src/parameterized_tendencies/radiation/RRTMGPInterface.jl
  src/parameterized_tendencies/radiation/radiation.jl
  src/parameterized_tendencies/radiation/radiation_utilities.jl
Labels: Refactor

#3694 Refactor RRTMGP interface
  src/parameterized_tendencies/radiation/RRTMGPInterface.jl
Labels: Refactor

#3695 Test that ClimaAtmos is developed in buildkite pipeline
  .buildkite/pipeline.yml
Labels: Tests

#3692 Move precipitation cache to precomputed quantities
  .buildkite/Manifest-v1.11.toml
  NEWS.md
  Project.toml
  src/cache/cache.jl
  src/cache/precipitation_precomputed_quantities.jl
  src/cache/precomputed_quantities.jl
  src/diagnostics/core_diagnostics.jl
  src/parameterized_tendencies/microphysics/precipitation.jl
  src/prognostic_equations/surface_temp.jl
  test/coupler_compatibility.jl
  test/parameterized_tendencies/microphysics/precipitation.jl
  test/restart.jl
Labels: Microphysics

#3698 Encapsulate rrtmgp model kwargs
  src/callbacks/callbacks.jl
  src/compat.jl
  src/parameterized_tendencies/radiation/RRTMGPInterface.jl
  src/parameterized_tendencies/radiation/radiation.jl
Labels: Refactor

#3716 Surface cloud sedimentation included in precipitation fluxes
  src/cache/precipitation_precomputed_quantities.jl
Labels: Microphysics

#3725 Print at exit only on buildkite
  src/solver/type_getters.jl
Labels: Logging :ledger:

#3717 Remove dt_save_to_sol
  NEWS.md
  calibration/experiments/gcm_driven_scm/model_config_prognostic.yml
  config/default_configs/default_config.yml
  config/gpu_configs/baroclinic_wave_helem30.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_diag_1process.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ss.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_summer.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ws_1process.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ws_2process.yml
  config/gpu_configs/gpu_aquaplanet_dyamond_ws_4process.yml
  config/gpu_configs/held_suarez_equil_helem30.yml
  config/mbw_scaling_configs/moist_baroclinic_wave_helem_120_0M_ss.yml
  config/mbw_scaling_configs/moist_baroclinic_wave_helem_120_0M_ws.yml
  config/mbw_scaling_configs/moist_baroclinic_wave_helem_170_0M_ws.yml
  config/mbw_scaling_configs/moist_baroclinic_wave_helem_240_0M_ss.yml
  config/mbw_scaling_configs/moist_baroclinic_wave_helem_240_0M_ws.yml
  config/mbw_scaling_configs/moist_baroclinic_wave_helem_30_0M_ss.yml
  config/mbw_scaling_configs/moist_baroclinic_wave_helem_30_0M_ws.yml
  config/mbw_scaling_configs/moist_baroclinic_wave_helem_340_0M_ws.yml
  config/mbw_scaling_configs/moist_baroclinic_wave_helem_42_0M_ws.yml
  config/mbw_scaling_configs/moist_baroclinic_wave_helem_480_0M_ws.yml
  config/mbw_scaling_configs/moist_baroclinic_wave_helem_60_0M_ss.yml
  config/mbw_scaling_configs/moist_baroclinic_wave_helem_60_0M_ws.yml
  config/mbw_scaling_configs/moist_baroclinic_wave_helem_84_0M_ws.yml
  config/model_configs/single_column_hydrostatic_balance_ft64.yml
  config/model_configs/single_column_radiative_equilibrium_allsky_idealized_clouds.yml
  config/model_configs/single_column_radiative_equilibrium_clearsky.yml
  config/model_configs/single_column_radiative_equilibrium_clearsky_prognostic_surface_temp.yml
  config/model_configs/single_column_radiative_equilibrium_gray.yml
  config/model_configs/test_env.yml
  config/perf_configs/bm_aquaplanet_diagedmf.yml
  config/perf_configs/bm_aquaplanet_progedmf.yml
  config/perf_configs/bm_baroclinic_wave_moist.yml
  config/perf_configs/bm_callbacks.yml
  config/perf_configs/bm_default.yml
  config/perf_configs/bm_default_1m.yml
  config/perf_configs/bm_diagnostics.yml
  config/perf_configs/bm_diffusion.yml
  config/perf_configs/bm_gravity_wave.yml
  docs/src/radiative_equilibrium.md
  src/solver/type_getters.jl
Labels: Breaking :boom:

#3730 Upgrade all deps, except ClimaCore
  .buildkite/Manifest-v1.11.toml
Labels: Dependencies :spider_web:

#3705 Prognostic EDMF + 1M
  .buildkite/pipeline.yml
  config/model_configs/prognostic_edmfx_rico_column.yml
  config/model_configs/prognostic_edmfx_trmm_column.yml
  post_processing/ci_plots.jl
  src/cache/precipitation_precomputed_quantities.jl
  src/cache/precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/diagnostics/edmfx_diagnostics.jl
  src/initial_conditions/atmos_state.jl
  src/parameterized_tendencies/microphysics/precipitation.jl
  src/prognostic_equations/advection.jl
  src/prognostic_equations/edmfx_entr_detr.jl
  src/prognostic_equations/edmfx_precipitation.jl
  src/prognostic_equations/edmfx_sgs_flux.jl
  src/prognostic_equations/hyperdiffusion.jl
  src/prognostic_equations/implicit/implicit_solver.jl
  src/utils/variable_manipulations.jl
Labels: Microphysics

#3709 Update dependencies
  .buildkite/Manifest-v1.11.toml
  reproducibility_tests/ref_counter.jl
Labels: Dependencies :spider_web:

#3743 calibratable number_conc for r_eff
  .buildkite/Manifest-v1.11.toml
  Project.toml
  src/callbacks/callbacks.jl
  src/parameterized_tendencies/microphysics/microphysics_wrappers.jl
  src/parameters/create_parameters.jl
Labels: Microphysics

#3752 add back derivative of rhoq to rho
  src/prognostic_equations/implicit/implicit_solver.jl
Labels: bugfix :bug: :hammer:
