Repository CliMA/ClimaAtmos.jl, pull requests merged in 2025-04, with the labels that each got.

#3763 use lazy broadcasting instead of temp scalar in implicit solver
  reproducibility_tests/ref_counter.jl
  src/prognostic_equations/implicit/implicit_solver.jl
Labels: bugfix :bug: :hammer:

#3758 Adds ERA5 Time Varying Forcing driven in the single column setting
  .buildkite/pipeline.yml
  Artifacts.toml
  NEWS.md
  config/default_configs/default_config.yml
  config/model_configs/prognostic_edmfx_tv_era5driven_column.yml
  docs/make.jl
  docs/src/single_column_prospect.md
  post_processing/ci_plots.jl
  src/ClimaAtmos.jl
  src/cache/cache.jl
  src/callbacks/callbacks.jl
  src/callbacks/get_callbacks.jl
  src/initial_conditions/InitialConditions.jl
  src/initial_conditions/initial_conditions.jl
  src/prognostic_equations/forcing/external_forcing.jl
  src/solver/model_getters.jl
  src/solver/type_getters.jl
  src/solver/types.jl
  src/surface_conditions/SurfaceConditions.jl
  src/surface_conditions/surface_conditions.jl
  src/surface_conditions/surface_setups.jl
  src/utils/era5_observations_to_forcing_file.jl
  test/utilities.jl
  toml/prognostic_edmfx_calibrated.toml
Labels: enhancement

#3775 Support for intermittent calls to update non-orographic gravity wave tendencies (Replacement for #3761)
  NEWS.md
  config/default_configs/default_config.yml
  config/model_configs/single_column_nonorographic_gravity_wave.yml
  config/model_configs/sphere_nonorographic_gravity_wave.yml
  docs/src/diagnostics.md
  docs/src/gravity_wave.md
  reproducibility_tests/ref_counter.jl
  src/callbacks/callbacks.jl
  src/callbacks/get_callbacks.jl
  src/diagnostics/Diagnostics.jl
  src/diagnostics/diagnostic.jl
  src/diagnostics/gravitywave_diagnostics.jl
  src/parameterized_tendencies/gravity_wave_drag/non_orographic_gravity_wave.jl
  src/solver/model_getters.jl
  src/solver/types.jl
Labels: enhancement, Refactor, gravity wave, Diagnostics
