Repository CliMA/ClimaAtmos.jl, pull requests merged in 2025-02, with the labels that each got.

#3572 Bugfix for coupler
  src/parameterized_tendencies/microphysics/precipitation.jl
Labels: Microphysics, bugfix :bug: :hammer:

#3569 Use lazy-broadcast for vertical transport terms
  src/prognostic_equations/advection.jl
  src/prognostic_equations/edmfx_sgs_flux.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
Labels: Refactor

#3573 Use LazyBroadcast for `set_u_h`
  src/ClimaAtmos.jl
  src/cache/precomputed_quantities.jl
Labels: Refactor

#3575 Use LazyBroadcast for strain_rate methods
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/prognostic_equations/edmfx_sgs_flux.jl
  src/prognostic_equations/gm_sgs_closures.jl
  src/prognostic_equations/vertical_diffusion_boundary_layer.jl
  src/utils/utilities.jl
  test/utilities.jl
Labels: Refactor

#3577 Use LazyBroadcast for parts of `eddy_diffusivity_coefficient`
  src/ClimaAtmos.jl
  src/cache/eddy_diffusivity_coefficient.jl
  src/cache/precomputed_quantities.jl
Labels: Refactor

#3578 Use LazyBroadcast for HS forcing
  src/ClimaAtmos.jl
  src/parameterized_tendencies/radiation/held_suarez.jl
  src/parameterized_tendencies/sponge/sponge_tendencies.jl
  src/prognostic_equations/remaining_tendency.jl
  test/parameterized_tendencies/forcing/held_suarez.jl
Labels: Refactor

#3580 Use LazyBroadcast for edmf coriolis
  src/cache/cache.jl
  src/prognostic_equations/edmf_coriolis.jl
  src/prognostic_equations/remaining_tendency.jl
  test/coupler_compatibility.jl
Labels: Refactor

#3582 Remove unused functions
  src/cache/precomputed_quantities.jl
Labels: House cleaning :broom:

#3598 Use NullBroadcasts.jl
  .buildkite/Manifest-v1.11.toml
  .buildkite/Project.toml
  Project.toml
  src/ClimaAtmos.jl
  src/null_broadcasted.jl
  test/Project.toml
  test/dependencies.jl
  test/parameterized_tendencies/sponge/rayleigh_sponge.jl
Labels: Refactor

#3602 Advection of water with working fluid changes
  src/ClimaAtmos.jl
  src/cache/diagnostic_edmf_precomputed_quantities.jl
  src/cache/precipitation_precomputed_quantities.jl
  src/cache/precomputed_quantities.jl
  src/cache/prognostic_edmf_precomputed_quantities.jl
  src/parameters/create_parameters.jl
  src/prognostic_equations/implicit/implicit_solver.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/prognostic_equations/remaining_tendency.jl
  src/prognostic_equations/water_advection.jl
Labels: Microphysics

#3607 Bump CloudMicrophysics minimal version
  Project.toml
Labels: Microphysics

#3609 Use test_all for aqua tests
  test/aqua.jl
Labels: Tests

#3620 Prescribe effective radius, add to diagnostics output
  .buildkite/Manifest-v1.11.toml
  Project.toml
  config/model_configs/sphere_aquaplanet_rhoe_nonequilmoist_allsky.yml
  src/callbacks/callbacks.jl
  src/diagnostics/radiation_diagnostics.jl
  toml/sphere_aquaplanet.toml
  toml/sphere_aquaplanet_1M.toml
Labels: Microphysics

#3635 clean up model_configs
  .buildkite/longruns_gpu/pipeline.yml
  .buildkite/pipeline.yml
  config/longrun_configs/longrun_hydrostatic_balance.yml
  config/longrun_configs/longrun_zalesak_tracer_energy_bw_rhoe_equil_highres.yml
  config/model_configs/aquaplanet_equil_allsky_gw_raw_zonalasym.yml
  config/model_configs/aquaplanet_equil_clearsky_tvinsol_0M_slabocean.yml
  config/model_configs/aquaplanet_equil_clearsky_tvinsol_0M_slabocean_ft64.yml
  config/model_configs/aquaplanet_nonequil_allsky_gw_res.yml
  config/model_configs/baroclinic_wave.yml
  config/model_configs/baroclinic_wave_conservation.yml
  config/model_configs/baroclinic_wave_equil.yml
  config/model_configs/baroclinic_wave_equil_conservation.yml
  config/model_configs/baroclinic_wave_equil_conservation_ft64.yml
  config/model_configs/baroclinic_wave_equil_conservation_source.yml
  config/model_configs/baroclinic_wave_equil_earth.yml
  config/model_configs/baroclinic_wave_hughes2023.yml
  config/model_configs/baroclinic_wave_topography_dcmip_rs.yml
  config/model_configs/box_hydrostatic_balance.yml
  config/model_configs/cloud_diag_gpu_hs_equil_0M.yml
  config/model_configs/gpu_hs_equil_0M.yml
  config/model_configs/held_suarez.yml
  config/model_configs/held_suarez_equil.yml
  config/model_configs/hydrostatic_balance_ft64.yml
  config/model_configs/sphere_aquaplanet_rhoe_nonequilmoist_allsky.yml
  config/model_configs/sphere_ssp_baroclinic_wave_rhoe_equilmoist_earth.yml
  config/mpi_configs/mpi_aquaplanet_equil_clearsky.yml
  config/mpi_configs/restart_mpi_baroclinic_wave.yml
  docs/src/longruns.md
  post_processing/ci_plots.jl
  reproducibility_tests/ref_counter.jl
  reproducibility_tests/reproducibility_test_job_ids.jl
Labels: House cleaning :broom:

#3642 Update dependencies
  .buildkite/Manifest-v1.11.toml
  perf/benchmark.jl
  reproducibility_tests/ref_counter.jl
Labels: Dependencies :spider_web:

#3644 Bugfix: DYAMOND ic with EDOnly
  config/gpu_configs/gpu_aquaplanet_dyamond_summer.yml
  src/initial_conditions/initial_conditions.jl
Labels: bugfix :bug: :hammer:

#3661 Add density in cloud condensate RHS
  src/parameterized_tendencies/microphysics/cloud_condensate.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
  src/prognostic_equations/remaining_tendency.jl
  test/parameterized_tendencies/microphysics/precipitation.jl
  toml/longrun_aquaplanet_1M.toml
  toml/longrun_baroclinic_wave_1M.toml
  toml/sphere_aquaplanet_1M.toml
Labels: Microphysics
