Repository CliMA/ClimaAtmos.jl, pull requests merged in 2025-01, with the labels that each got.

#3521 WIP on updating velocities for dycore paper
  config/model_configs/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_res.yml
  reproducibility_tests/ref_counter.jl
  src/cache/precipitation_precomputed_quantities.jl
  src/cache/precomputed_quantities.jl
  src/prognostic_equations/implicit/implicit_solver.jl
  src/prognostic_equations/implicit/implicit_tendency.jl
Labels: Microphysics

#3541 A LazyBroadcast as a dependency
  .dev/Manifest.toml
  Project.toml
  docs/Manifest-v1.11.toml
  docs/Manifest.toml
  docs/Project.toml
  examples/Manifest-v1.11.toml
  examples/Manifest.toml
  examples/Project.toml
  perf/Manifest-v1.11.toml
  perf/Manifest.toml
  perf/Project.toml
  src/ClimaAtmos.jl
  test/Project.toml
  test/dependencies.jl
Labels: Dependencies :spider_web:

#3543 Upgrade manifests
  .dev/Manifest-v1.11.toml
  docs/Manifest-v1.11.toml
  docs/Manifest.toml
  examples/Manifest-v1.11.toml
  examples/Manifest.toml
  perf/Manifest-v1.11.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#3551 Update dependencies
  docs/Manifest-v1.11.toml
  examples/Manifest-v1.11.toml
  perf/Manifest-v1.11.toml
Labels: Dependencies :spider_web:

#3561 Add buildkite project
  .buildkite/Manifest-v1.11.toml
  .buildkite/Project.toml
Labels: Dependencies :spider_web:

#3540 Use LazyBroadcast for tendencies
  reproducibility_tests/ref_counter.jl
  src/ClimaAtmos.jl
  src/null_broadcasted.jl
  src/parameterized_tendencies/sponge/rayleigh_sponge.jl
  src/parameterized_tendencies/sponge/sponge_tendencies.jl
  src/parameterized_tendencies/sponge/viscous_sponge.jl
  src/prognostic_equations/remaining_tendency.jl
  test/parameterized_tendencies/sponge/rayleigh_sponge.jl
  test/parameterized_tendencies/sponge/viscous_sponge.jl
Labels: Refactor, design, Performance
